# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Gesgp7Vc_RTOr6WZrQUkrqCCKdTXMno
"""



import streamlit as st
import pandas as pd
import numpy as np

# Configuración general de la página en modo ancho
st.set_page_config(
    page_title="Simulador proceso Azucarera ACOR",
    page_icon="🏭",
    layout="wide"
)

# ====================================================================
# 0. CATÁLOGO MAESTRO DE VAPORES Y ENERGÍAS DINÁMICAS
# ====================================================================
CATALOGO_VAPORES = {
    'Vapor_1': {'entalpia': 2210.0, 'tanque_destino': 'Calderas_4056'},
    'Vapor_2': {'entalpia': 2255.0, 'tanque_destino': 'Tanque_9635'},
    'Vapor_3': {'entalpia': 2290.0, 'tanque_destino': 'Tanque_9635'},
    'Vapor_4': {'entalpia': 2315.0, 'tanque_destino': 'Tanque_9635'},
    'Vapor_5': {'entalpia': 2340.0, 'tanque_destino': 'Tanque_9635'},
    'Vapor_6': {'entalpia': 2340.0, 'tanque_destino': 'Tanque_9635'},
    'Vahos_Tachas': {'entalpia': 2365.0, 'tanque_destino': 'Tanque_A.AG5_PanCondensate'},
    'Condensados': {'entalpia': 393.0, 'tanque_destino': 'Retorno_Estacion_Condensados'},
    'Vapor_Escape': {'entalpia': 2200.0, 'tanque_destino': 'Calderas'},
    # Compatibilidad con nomenclaturas anteriores
    'Vapor_1erEfecto': {'entalpia': 2210.0, 'tanque_destino': 'Calderas_4056'},
    'Vapor_2doEfecto': {'entalpia': 2255.0, 'tanque_destino': 'Tanque_9635'},
    'Vapor_3erEfecto': {'entalpia': 2290.0, 'tanque_destino': 'Tanque_9635'},
    'Vapor_4toEfecto': {'entalpia': 2315.0, 'tanque_destino': 'Tanque_9635'},
    'Vapor_5toEfecto': {'entalpia': 2340.0, 'tanque_destino': 'Tanque_9635'},
    'Vapor_6toEfecto': {'entalpia': 2340.0, 'tanque_destino': 'Tanque_9635'},
    'Vapor_V5_A609': {'entalpia': 2340.0, 'tanque_destino': 'Tanque_A.609'},
    'Vapor_V6_94C': {'entalpia': 2275.0, 'tanque_destino': 'Tanque_A.AG6_WarmWater'},
    'Vapor_Tachas_57C': {'entalpia': 2365.0, 'tanque_destino': 'Tanque_A.AG5_PanCondensate'},
    'Condensado_A609_Sensible': {'entalpia': 179.3, 'tanque_destino': 'Tanque_A.AG6_WarmWater'}
}

LISTA_TIPOS_VAPOR = list(CATALOGO_VAPORES.keys())

# ====================================================================
# MOTOR MATEMÁTICO ÍNTEGRO (MÓDULOS 1 AL 8)
# ====================================================================
class PlantaAzucareraCompleta:
    def __init__(self, config=None):
        self.config = {
            'Molienda t/h': 550.00,
            'Riqueza_Remolacha': 17.40,
            'Pureza_Agricola': 90.40,
            'Marco_Remolacha': 4.50,

            # --- MÓDULO 1: DIFUSIÓN Y PRENSAS ---
            'Draft': 1.11,
            'MS_PulpaPrensada': 27.50,
            'Tª_Jugo_Verde': 26.00,
            '% Ratio_Agua_Aporte': 24.93,
            'OP_DifPren_Mezcla_AguaCaliente_pct': 80.00,
            'OP_DifPren_Ratio_AguaPrensas_pct': 37.04,
            'OP_DifPren_Ratio_Recirculacion_pct': 165.00,
            'OP_DifPren_Ratio_Desespumador_pct': 46.00,
            'Intercambiador 17_Tª Entrada_C': 62.00,
            'OP_DifPren_Int17_Tª Salida_C': 72.00,
            'OP_DifPren_Int18_19_TempIn_C': 71.40,
            'OP_DifPren_Int18_19_TempOut_C': 73.30,
            'OP_DifPren_Int20_TempIn_C': 71.40,
            'OP_DifPren_Int20_TempOut_C': 76.50,
            'OP_DifPren_Int17_FuenteVapor': 'Vapor_5',
            'OP_DifPren_Int18_19_FuenteVapor': 'Vapor_V5_A609',
            'OP_DifPren_Int20_FuenteVapor': 'Vapor_V5_A609',

            # --- MÓDULO 2: CALENTAMIENTO JUGO VERDE (Nº 00, 0, 1, 2, 3, 3A) ---
            'OP_Cal_Verde_Int00_TempOut_C': 47.40,
            'OP_Cal_Verde_Int0_TempOut_C': 48.80,
            'OP_Cal_Verde_Int1_TempOut_C': 49.10,
            'OP_Cal_Verde_Int2_TempOut_C': 49.10,
            'OP_Cal_Verde_Int3_TempOut_C': 53.80,
            'OP_Cal_Verde_Int3a_TempOut_C': 59.00,
            'OP_Cal_Verde_Int00_FuenteVapor': 'Vahos_Tachas',
            'OP_Cal_Verde_Int0_FuenteVapor': 'Vahos_Tachas',
            'OP_Cal_Verde_Int1_FuenteVapor': 'Vahos_Tachas',
            'OP_Cal_Verde_Int2_FuenteVapor': 'Vahos_Tachas',
            'OP_Cal_Verde_Int3_FuenteVapor': 'Vapor_6',
            'OP_Cal_Verde_Int3a_FuenteVapor': 'Condensado_A609_Sensible',

            # --- MÓDULO 3: DEPURACIÓN Y TREN TÉRMICO (Nº 3B, 4, 5, 6, 7, 8, 9) ---
            'OP_Depuracion_CaO_pct_remolacha': 1.28,
            'OP_AzucarCorefin_th': 8.80,
            'OP_1raCarb_AlcalinidadEntrada_gh': 2.50,
            'OP_1raCarb_AlcalinidadSalida': 0.90,
            'OP_2daCarb_AlcalinidadSalida': 0.27,
            'OP_PKF_MS_Barros_pct': 64.90,
            'OP_Calent_3B_TempEntrada_C': 61.40,
            'OP_Calent_3B_TempSalida_C': 65.50,
            'OP_Calent_4_TempSalida_C': 82.30,
            'OP_Calent_56_TempSalida_C': 87.80,
            'OP_Calent_7_TempSalida_C': 87.80,
            'OP_Enfriamiento_1raCarb_C': 1.60,
            'OP_Enfriamiento_1raFiltracion_C': 1.00,
            'OP_Enfriamiento_2daCarb_C': 4.70,
            'OP_Calent_No8_TempSalida_C': 86.20,
            'OP_Calent_No9_TempSalida_C': 92.00,
            'OP_CalorEspecifico_Jugo_kWh_tC': 1.069,
            'OP_JugoFino_DestinoMelting_pct': 0.00,
            'OP_Vapor_Calentador_3B': 'Condensados',
            'OP_Vapor_Calentador_4': 'Vapor_6',
            'OP_Vapor_Calentador_56': 'Vapor_5',
            'OP_Vapor_Calentador_7': 'Vapor_4',
            'OP_Vapor_Calentador_No8': 'Vapor_5',
            'OP_Vapor_Calentador_No9': 'Vapor_3',

            # --- MÓDULO 4: CALENTAMIENTO JUGO FINO (Nº 10, 11, 12, 13, 14) ---
            'OP_Calentador10_TempSalida_C': 117.30,
            'OP_Calentador11_12_TempSalida_C': 121.60,
            'OP_Calentador13_TempSalida_C': 123.80,
            'OP_Calentador14_TempSalida_C': 123.80,
            'OP_Vapor_Calentador10': 'Vapor_3',
            'OP_Vapor_Calentador11_12': 'Vapor_2',
            'OP_Vapor_Calentador13': 'Vapor_1',
            'OP_Vapor_Calentador14': 'Vapor_Escape',
            'OP_CalorEspecifico_JugoFino_kWh_tC': 1.069,

            # --- MÓDULO 5: EVAPORACIÓN ---
            'OP_Evaporacion_BrixSalida_objetivo_pct': 69.40,

            # --- MÓDULO 6: CASA DE COCIMIENTO Y CRISTALIZACIÓN ---
            'OP_Cocimiento_RendimientoA_pct': 50.00,
            'OP_Cocimiento_RendimientoB_pct': 47.00,
            'OP_Cocimiento_RendimientoC_pct': 36.80,
            'OP_Cocimiento_BrixMasaA_pct': 91.00,
            'OP_Cocimiento_BrixMasaB_pct': 94.60,
            'OP_Cocimiento_BrixMasaC_pct': 95.30,

            # --- MÓDULO 7: REFUNDICIÓN & RECALENTADOR 15 ---
            'OP_Calentador15_Vapor_Fuente': 'Vapor_4',

            # --- MÓDULO 8: SECADERO DE PULPA Y ENERGÍA ---
            'OP_Pulpa_HumedadPellet_pct': 10.00,
            'OP_SecaderoPulpa_PCI_Gas_kWh_m3': 10.50,
            'OP_SecaderoPulpa_RendimientoTérmico_pct': 85.00,
            'OP_Turbina_ConsumoEspecifico_kWh_tVapor': 45.00
        }
        if config:
            self.config.update(config)

    def simular(self):
        cfg = self.config
        cat_vap = CATALOGO_VAPORES
        res = {}
        molienda = cfg['Molienda t/h']
        f_escala = molienda / 550.0

        # MÓDULO 1: DIFUSIÓN Y PRENSAS
        flujo_jugo_verde = molienda * cfg['Draft']
        solidos_sacarosa = molienda * (cfg['Riqueza_Remolacha'] / cfg['Pureza_Agricola']) * 0.98
        ds_jugo_verde = (solidos_sacarosa / flujo_jugo_verde) * 100.0 if flujo_jugo_verde > 0 else 0
        pulpa_prensada_secado = (molienda * (cfg['Marco_Remolacha']/100.0)) / (cfg['MS_PulpaPrensada']/100.0)

        flujo_agua_total = molienda * (cfg['% Ratio_Agua_Aporte'] / 100.0)
        agua_aporte_cal = flujo_agua_total * (cfg['OP_DifPren_Mezcla_AguaCaliente_pct'] / 100.0)
        agua_aporte_rio = flujo_agua_total - agua_aporte_cal

        f_agua_pren = molienda * (cfg['OP_DifPren_Ratio_AguaPrensas_pct']/100.0)
        f_recirc = molienda * (cfg['OP_DifPren_Ratio_Recirculacion_pct']/100.0)
        f_desesp = molienda * (cfg['OP_DifPren_Ratio_Desespumador_pct']/100.0)

        # Cálculo con entalpía dinámica seleccionada para Intercambiadores 17, 18+19, 20
        h_17 = cat_vap.get(cfg['OP_DifPren_Int17_FuenteVapor'], cat_vap['Vapor_5'])['entalpia']
        dt_17 = cfg['OP_DifPren_Int17_Tª Salida_C'] - cfg['Intercambiador 17_Tª Entrada_C']
        demanda_v17 = (f_agua_pren * 4.05 * dt_17) / h_17

        h_18 = cat_vap.get(cfg['OP_DifPren_Int18_19_FuenteVapor'], cat_vap['Vapor_V5_A609'])['entalpia']
        dt_18_19 = cfg['OP_DifPren_Int18_19_TempOut_C'] - cfg['OP_DifPren_Int18_19_TempIn_C']
        demanda_v18_19 = (f_recirc * 3.95 * dt_18_19) / h_18

        h_20 = cat_vap.get(cfg['OP_DifPren_Int20_FuenteVapor'], cat_vap['Vapor_V5_A609'])['entalpia']
        dt_20 = cfg['OP_DifPren_Int20_TempOut_C'] - cfg['OP_DifPren_Int20_TempIn_C']
        demanda_v20 = (f_desesp * 4.10 * dt_20) / h_20

        res['M1'] = {
            'OUT_CanaProcesada_th': molienda,
            'OUT_DifPren_Jugo_Verde_Flujo_th': round(flujo_jugo_verde, 2),
            'OUT_DifPren_Jugo_Verde_DS_pct': round(ds_jugo_verde, 2),
            'OUT_DifPren_Jugo_Verde_Pureza_pct': round(cfg['Pureza_Agricola'], 2),
            'OUT_DifPren_Jugo_Verde_Temp_C': round(cfg['Tª_Jugo_Verde'], 2),
            'OUT_DifPren_PulpaPrensada_Secado_th': round(pulpa_prensada_secado, 2),
            'OUT_DifPren_AguaAporte_Total_th': round(flujo_agua_total, 2),
            'OUT_DifPren_AguaAporte_Cal_th': round(agua_aporte_cal, 2),
            'OUT_DifPren_AguaAporte_Rio_th': round(agua_aporte_rio, 2),
            'OUT_DifPren_AguaPrensas_Flujo_th': round(f_agua_pren, 2),
            'OUT_DifPren_Recirculacion_Flujo_th': round(f_recirc, 2),
            'OUT_DifPren_Desespumador_Flujo_th': round(f_desesp, 2),
            'OUT_DifPren_Int17_DemandaVapor_th': round(demanda_v17, 2),
            'OUT_DifPren_Int18_19_DemandaVapor_th': round(demanda_v18_19, 2),
            'OUT_DifPren_Int20_DemandaVapor_th': round(demanda_v20, 2)
        }

        # MÓDULO 2: CALENTAMIENTO JUGO VERDE (Nº 00, 0, 1, 2, 3, 3A con entalpía dinámica)
        cp_jugo = 4.18 - (0.023 * ds_jugo_verde)
        t_in = cfg['Tª_Jugo_Verde']
        m2_out = {}
        for eq in ['00', '0', '1', '2', '3']:
            t_out = cfg[f'OP_Cal_Verde_Int{eq}_TempOut_C']
            dt = t_out - t_in
            fuente = cfg[f'OP_Cal_Verde_Int{eq}_FuenteVapor']
            h_eq = cat_vap.get(fuente, cat_vap['Vapor_Escape'])['entalpia']
            dem_v = (flujo_jugo_verde * cp_jugo * dt) / h_eq
            m2_out[f'OUT_Cal_Verde_Int{eq}_DemandaVapor_th'] = round(dem_v, 2)
            m2_out[f'OUT_Cal_Verde_Int{eq}_FuenteUsada'] = fuente
            t_in = t_out

        t_out_3a = cfg['OP_Cal_Verde_Int3a_TempOut_C']
        dt_3a = t_out_3a - t_in
        fuente_3a = cfg['OP_Cal_Verde_Int3a_FuenteVapor']
        h_3a = cat_vap.get(fuente_3a, cat_vap['Condensado_A609_Sensible'])['entalpia']
        demanda_liq = (flujo_jugo_verde * cp_jugo * dt_3a) / h_3a
        m2_out['OUT_Cal_Verde_Int3a_DemandaLíquido_th'] = round(demanda_liq, 2)
        m2_out['OUT_Cal_Verde_TempFinal_C'] = round(t_out_3a, 2)
        m2_out['OUT_Cal_Verde_FlujoSalida_th'] = round(flujo_jugo_verde, 2)
        m2_out['OUT_Cal_Verde_DS_Salida_pct'] = round(ds_jugo_verde, 2)
        res['M2'] = m2_out

        # MÓDULO 3: DEPURACIÓN Y CARBONATACIONES (Nº 3B, 4, 5+6, 7, 8, 9 con entalpía dinámica)
        cp_j = cfg['OP_CalorEspecifico_Jugo_kWh_tC']
        cao_activo = molienda * (cfg['OP_Depuracion_CaO_pct_remolacha'] / 100.0)
        pureza_base = cfg['Pureza_Agricola']
        lodos_2do = molienda * 0.0610
        agua_dilucion_lechada = 33.77 * f_escala
        lechada_total = cao_activo + agua_dilucion_lechada
        lechada_pre = lechada_total * (9.47 / (9.47 + 30.00))
        lechada_frio = lechada_total * (30.00 / (9.47 + 30.00))

        flujo_pre = flujo_jugo_verde + lodos_2do + lechada_pre
        ms_pre = (flujo_jugo_verde * (ds_jugo_verde / 100.0)) + (cao_activo * 0.5)
        brix_pre = (ms_pre / flujo_pre) * 100.0

        azucar_corefin = cfg['OP_AzucarCorefin_th'] * f_escala
        flujo_post_pre = flujo_pre + azucar_corefin
        ms_post_pre = ms_pre + azucar_corefin

        flujo_enc_frio = flujo_post_pre + lechada_frio
        ms_frio = ms_post_pre + (cao_activo * 0.5)
        brix_frio = (ms_frio / flujo_enc_frio) * 100.0

        # Calentador 3B
        t_out_3b = cfg['OP_Calent_3B_TempSalida_C']
        carga_3b = flujo_enc_frio * cp_j * (t_out_3b - cfg['OP_Calent_3B_TempEntrada_C'])
        fuente_3b = cfg['OP_Vapor_Calentador_3B']
        h_3b = cat_vap.get(fuente_3b, cat_vap['Condensados'])['entalpia']
        vap_3b = carga_3b / h_3b

        # Calentador 4
        t_out_4 = cfg['OP_Calent_4_TempSalida_C']
        carga_4 = flujo_enc_frio * cp_j * (t_out_4 - t_out_3b)
        fuente_4 = cfg['OP_Vapor_Calentador_4']
        h_4 = cat_vap.get(fuente_4, cat_vap['Vapor_4'])['entalpia']
        vap_4 = carga_4 / h_4

        # Calentadores 5+6
        t_out_56 = cfg['OP_Calent_56_TempSalida_C']
        carga_56 = flujo_enc_frio * cp_j * (t_out_56 - t_out_4)
        fuente_56 = cfg['OP_Vapor_Calentador_56']
        h_56 = cat_vap.get(fuente_56, cat_vap['Vapor_5'])['entalpia']
        vap_56 = carga_56 / h_56

        # Calentador 7
        t_out_7 = cfg['OP_Calent_7_TempSalida_C']
        carga_7 = flujo_enc_frio * cp_j * (t_out_7 - t_out_56)
        fuente_7 = cfg['OP_Vapor_Calentador_7']
        h_7 = cat_vap.get(fuente_7, cat_vap['Vapor_4'])['entalpia']
        vap_7 = carga_7 / h_7

        rel_esteq = 44.0 / 56.0
        alc_neut = max(0.0, cfg['OP_1raCarb_AlcalinidadEntrada_gh'] - cfg['OP_1raCarb_AlcalinidadSalida'])
        co2_1 = (flujo_enc_frio * alc_neut * rel_esteq) / 100.0
        t_out_1ra = t_out_7 - cfg['OP_Enfriamiento_1raCarb_C']

        flujo_react_1ra = flujo_enc_frio + co2_1
        barros_1ro = (flujo_react_1ra * 0.0477) / (1.0 - 0.0477)

        solidos_secos_pkf = (17.70 * f_escala) * 0.649
        barros_pkf = solidos_secos_pkf / (cfg['OP_PKF_MS_Barros_pct'] / 100.0)
        filtrato_pkf = barros_1ro - barros_pkf

        flujo_dep2160 = flujo_react_1ra + filtrato_pkf
        flujo_1ra_filt = flujo_dep2160 - barros_1ro

        # Calentador Nº 8
        t_out_no8 = cfg['OP_Calent_No8_TempSalida_C']
        carga_no8 = flujo_dep2160 * cp_j * (t_out_no8 - t_out_1ra)
        fuente_no8 = cfg['OP_Vapor_Calentador_No8']
        h_no8 = cat_vap.get(fuente_no8, cat_vap['Vapor_5'])['entalpia']
        vap_no8 = carga_no8 / h_no8

        t_out_1ra_filt = t_out_no8 - cfg['OP_Enfriamiento_1raFiltracion_C']

        # Calentador Nº 9
        t_out_no9 = cfg['OP_Calent_No9_TempSalida_C']
        carga_no9 = flujo_1ra_filt * cp_j * (t_out_no9 - t_out_1ra_filt)
        fuente_no9 = cfg['OP_Vapor_Calentador_No9']
        h_no9 = cat_vap.get(fuente_no9, cat_vap['Vapor_3'])['entalpia']
        vap_no9 = carga_no9 / h_no9

        co2_2 = max(0.0, (alc_neut - cfg['OP_1raCarb_AlcalinidadSalida'])) * rel_esteq
        t_out_2da = t_out_no9 - cfg['OP_Enfriamiento_2daCarb_C']

        flujo_2da_carb = flujo_1ra_filt + co2_2
        flujo_jugo_fino_total = flujo_2da_carb - lodos_2do
        pct_melting = cfg['OP_JugoFino_DestinoMelting_pct']
        flujo_jugo_fino_melting = flujo_jugo_fino_total * (pct_melting / 100.0)
        flujo_jugo_fino_mod4 = flujo_jugo_fino_total - flujo_jugo_fino_melting

        res['M3'] = {
            'OUT_Depuracion_CaO_Activo_th': round(cao_activo, 2),
            'OUT_Depuracion_JugoEntrada_th': round(flujo_jugo_verde, 2),
            'OUT_Depuracion_TempEntrada_C': round(t_out_3a, 2),
            'OUT_Depuracion_BrixEntrada_pct': round(ds_jugo_verde, 2),
            'OUT_Preencalado_Lechada_Calculada_th': round(lechada_pre, 2),
            'OUT_EncaladoFrio_Lechada_Calculada_th': round(lechada_frio, 2),
            'OUT_Preencalado_Salida_th': round(flujo_pre, 2),
            'OUT_Preencalado_Brix_pct': round(brix_pre, 2),
            'OUT_PostPreencalado_ConAzucar_th': round(flujo_post_pre, 2),
            'OUT_EncaladoFrio_Salida_th': round(flujo_enc_frio, 2),
            'OUT_EncaladoFrio_Brix_pct': round(brix_frio, 2),
            'OUT_Calent_3B_Carga_kWh': round(carga_3b, 2),
            'OUT_Calent_3B_Vapor_th': round(vap_3b, 2),
            'OUT_Calent_4_Carga_kWh': round(carga_4, 2),
            'OUT_Calent_4_Vapor_th': round(vap_4, 2),
            'OUT_Calent_56_Carga_kWh': round(carga_56, 2),
            'OUT_Calent_56_Vapor_th': round(vap_56, 2),
            'OUT_Calent_7_Carga_kWh': round(carga_7, 2),
            'OUT_Calent_7_Vapor_th': round(vap_7, 2),
            'OUT_1raCarb_CO2_th': round(co2_1, 2),
            'OUT_1raCarb_AlcalinidadSalida': round(cfg['OP_1raCarb_AlcalinidadSalida'], 2),
            'OUT_1raCarb_TempSalida_C': round(t_out_1ra, 2),
            'OUT_1raCarb_BarrosRecirc_th': round(barros_1ro, 2),
            'OUT_PKF_Filtrato_th': round(filtrato_pkf, 2),
            'OUT_PKF_Barros_th': round(barros_pkf, 2),
            'OUT_Deposito2160_Salida1raCarbConFiltrato_th': round(flujo_dep2160, 2),
            'OUT_Deposito2160_Brix_pct': round(brix_frio * 0.98, 2),
            'OUT_1raFiltracion_BarrosConcentrados_th': round(barros_1ro, 2),
            'OUT_1raFiltracion_JugoClaro_th': round(flujo_1ra_filt, 2),
            'OUT_Calent_No8_Carga_kWh': round(carga_no8, 2),
            'OUT_Calent_No8_Vapor_th': round(vap_no8, 2),
            'OUT_1raFiltracion_TempSalida_C': round(t_out_1ra_filt, 2),
            'OUT_Calent_No9_Carga_kWh': round(carga_no9, 2),
            'OUT_Calent_No9_Vapor_th': round(vap_no9, 2),
            'OUT_2daCarb_CO2_th': round(co2_2, 2),
            'OUT_2daCarb_TempSalida_C': round(t_out_2da, 2),
            'OUT_2daCarb_Salida_th': round(flujo_2da_carb, 2),
            'OUT_JugoFino_Total_th': round(flujo_jugo_fino_total, 2),
            'OUT_JugoFino_ParaMelting_th': round(flujo_jugo_fino_melting, 2),
            'OUT_JugoFino_ParaModulo4_Calentamiento_th': round(flujo_jugo_fino_mod4, 2),
            'OUT_JugoFino_Brix_pct': round(brix_frio * 0.98, 2),
            'OUT_JugoFino_Pureza_pct': round(pureza_base + 2.1, 2),
            'OUT_JugoFino_Temp_C': round(t_out_2da, 2)
        }

        # MÓDULO 4: CALENTAMIENTO JUGO FINO (Nº 10, 11+12, 13, 14 con entalpía dinámica)
        flujo_jf_m4 = res['M3']['OUT_JugoFino_ParaModulo4_Calentamiento_th']
        temp_ent_m4 = res['M3']['OUT_JugoFino_Temp_C']
        cp_jf = cfg['OP_CalorEspecifico_JugoFino_kWh_tC']

        t_out_10 = cfg['OP_Calentador10_TempSalida_C']
        carga_10 = flujo_jf_m4 * cp_jf * max(0.0, t_out_10 - temp_ent_m4)
        h_10 = cat_vap.get(cfg['OP_Vapor_Calentador10'], cat_vap['Vapor_3'])['entalpia']
        vap_10 = carga_10 / h_10

        t_out_11_12 = cfg['OP_Calentador11_12_TempSalida_C']
        carga_11_12 = flujo_jf_m4 * cp_jf * max(0.0, t_out_11_12 - t_out_10)
        h_11_12 = cat_vap.get(cfg['OP_Vapor_Calentador11_12'], cat_vap['Vapor_2'])['entalpia']
        vap_11_12 = carga_11_12 / h_11_12

        t_out_13 = cfg['OP_Calentador13_TempSalida_C']
        carga_13 = flujo_jf_m4 * cp_jf * max(0.0, t_out_13 - t_out_11_12)
        h_13 = cat_vap.get(cfg['OP_Vapor_Calentador13'], cat_vap['Vapor_1'])['entalpia']
        vap_13 = carga_13 / h_13

        t_out_14 = cfg['OP_Calentador14_TempSalida_C']
        carga_14 = flujo_jf_m4 * cp_jf * max(0.0, t_out_14 - t_out_13)
        h_14 = cat_vap.get(cfg['OP_Vapor_Calentador14'], cat_vap['Vapor_Escape'])['entalpia']
        vap_14 = carga_14 / h_14

        res['M4'] = {
            'IN_Mod4_JugoFinoFlujo_th': round(flujo_jf_m4, 2),
            'IN_Mod4_TempEntrada_C': round(temp_ent_m4, 2),
            'OUT_Calent10_Vapor_th': round(vap_10, 2),
            'OUT_Calent11_12_Vapor_th': round(vap_11_12, 2),
            'OUT_Calent13_Vapor_th': round(vap_13, 2),
            'OUT_Calent14_Vapor_th': round(vap_14, 2),
            'OUT_JugoFinoCalentado_Flujo_th': round(flujo_jf_m4, 2),
            'OUT_JugoFinoCalentado_Temp_C': round(t_out_14, 2),
            'OUT_JugoFinoCalentado_Brix_pct': round(res['M3']['OUT_JugoFino_Brix_pct'], 2),
            'OUT_JugoFinoCalentado_Pureza_pct': round(res['M3']['OUT_JugoFino_Pureza_pct'], 2)
        }

        # MÓDULO 6: CASA DE COCIMIENTO Y CRISTALIZACIÓN
        azucar_comercial = molienda * (cfg['Riqueza_Remolacha'] / 100.0) * 0.825
        polvo_secadero = 4.61 * f_escala
        azucar_b_fundicion = 32.48 * f_escala
        melaza_final = (molienda * 0.052) * f_escala

        v_tacha_a = 33.14 * f_escala
        v_tacha_b = 9.84 * f_escala
        v_tacha_c = 5.83 * f_escala

        res['M6'] = {
            'E1_Vapor_TachasA_th': round(v_tacha_a, 2),
            'E3_Vapor_TachasB_th': round(v_tacha_b, 2),
            'E5_Vapor_TachasC_th': round(v_tacha_c, 2),
            'OUT_Vapor4_Demanda_Total_th': round(v_tacha_a + v_tacha_c, 2),
            'OUT_Vapor3_Demanda_Total_th': round(v_tacha_b, 2),
            'OUT_AzucarComercial_Silo_th': round(azucar_comercial, 2),
            'OUT_PolvoSecadero_Recuperado_th': round(polvo_secadero, 2),
            'OUT_AzucarB_Fundicion_th': round(azucar_b_fundicion, 2),
            'OUT_AzucarB_Polarizacion_pct': 99.00,
            'OUT_MelazaFinal_th': round(melaza_final, 2),
            'OUT_SecaderoAzucar_Vapor_th': round(1.78 * f_escala, 2)
        }

        # MÓDULO 5: EVAPORACIÓN Y MATRIZ DE VAPORES
        flujo_m5_in = res['M4']['OUT_JugoFinoCalentado_Flujo_th']
        brix_m5_in = res['M4']['OUT_JugoFinoCalentado_Brix_pct']
        temp_m5_in = res['M4']['OUT_JugoFinoCalentado_Temp_C']
        pureza_m5_in = res['M4']['OUT_JugoFinoCalentado_Pureza_pct']

        ms_m5 = flujo_m5_in * (brix_m5_in / 100.0)
        brix_obj_m5 = cfg['OP_Evaporacion_BrixSalida_objetivo_pct']
        flujo_jarabe = ms_m5 / (brix_obj_m5 / 100.0)
        agua_evap_total = flujo_m5_in - flujo_jarabe

        evap_base = [107.73, 100.30, 96.61, 46.78, 4.43, 13.58]
        total_base_evap = sum(evap_base)
        factores_prop = [e / total_base_evap for e in evap_base]
        flash_base = [3.50, 3.10, 2.80, 2.10, 1.50, 0.50]
        escala_evap = agua_evap_total / 369.46

        temp_jugo_sal = [131.6, 127.3, 122.2, 116.5, 110.8, 99.5]
        temp_vap_ef = [131.0, 126.4, 120.2, 112.4, 106.5, 94.0]
        nombres_vaps = ['Vapor_1erEfecto', 'Vapor_2doEfecto', 'Vapor_3erEfecto', 'Vapor_4toEfecto', 'Vapor_5toEfecto', 'Vapor_6toEfecto']

        flujo_j_act = flujo_m5_in
        detalles_ef = {}
        oferta_vaps = {}
        oferta_flash = {}
        oferta_tot = {}

        for i in range(6):
            evap_i = agua_evap_total * factores_prop[i]
            flash_i = flash_base[i] * escala_evap
            v_tot_i = evap_i + flash_i
            flujo_j_act -= evap_i
            brix_i = (ms_m5 / flujo_j_act) * 100.0

            detalles_ef[f'Efecto_{i+1}'] = {
                'Jugo_Flujo_th': round(flujo_j_act, 2),
                'Jugo_Brix_pct': round(brix_i, 2),
                'Jugo_Pureza_pct': round(pureza_m5_in, 2),
                'Jugo_Temp_C': temp_jugo_sal[i],
                'Vapor_Generado_th': round(evap_i, 2),
                'Vapor_Flash_th': round(flash_i, 2),
                'Vapor_Total_th': round(v_tot_i, 2),
                'Vapor_Temp_C': temp_vap_ef[i],
                'Vapor_Tipo': nombres_vaps[i]
            }
            oferta_vaps[nombres_vaps[i]] = round(evap_i, 2)
            oferta_flash[nombres_vaps[i]] = round(flash_i, 2)
            oferta_tot[nombres_vaps[i]] = round(v_tot_i, 2)

        q_sens_m5 = (flujo_m5_in * 0.94 * (131.6 - temp_m5_in)) / 1000.0
        q_lat_m5 = (oferta_tot['Vapor_1erEfecto'] * 521.5) / 1000.0
        v_calderas = ((q_sens_m5 + q_lat_m5) * 1000.0) / 502.20

        res['M5'] = {
            'IN_Mod5_JugoFinoFlujo_th': round(flujo_m5_in, 2),
            'IN_Mod5_TempEntrada_C': round(temp_m5_in, 2),
            'IN_Mod5_Brix_pct': round(brix_m5_in, 2),
            'IN_Mod5_Pureza_pct': round(pureza_m5_in, 2),
            'OUT_Evaporacion_MasaSeca_th': round(ms_m5, 2),
            'OUT_ThickJuice_Flujo_th': round(flujo_jarabe, 2),
            'OUT_ThickJuice_Brix_pct': round(brix_obj_m5, 2),
            'OUT_ThickJuice_Pureza_pct': round(pureza_m5_in, 2),
            'OUT_ThickJuice_Temp_C': 99.50,
            'OUT_Evaporacion_AguaTotalEvaporada_th': round(agua_evap_total, 2),
            'OUT_Detalle_Etapas_Evaporacion': detalles_ef,
            'OUT_Mod5_OfertaVapores_th': oferta_vaps,
            'OUT_Mod5_OfertaFlash_th': oferta_flash,
            'OUT_Mod5_OfertaTotalVapores_th': oferta_tot,
            'OUT_Condensados_Calderas4056_th': round(oferta_tot['Vapor_1erEfecto'], 2),
            'OUT_Condensados_Tanque9635_th': round(agua_evap_total - oferta_tot['Vapor_1erEfecto'], 2),
            'OUT_VaporCalderas_1erEfecto_th': round(v_calderas, 2)
        }

        # MÓDULO 7: REFUNDICIÓN Y CONDENSADOS
        ms_jarabe = flujo_jarabe * (brix_obj_m5 / 100.0)
        ms_azucar_b = azucar_b_fundicion * 0.99
        ms_polvo = polvo_secadero * 1.0
        ms_total_melter = ms_jarabe + ms_azucar_b + ms_polvo
        brix_liquor_estandar = 66.50
        flujo_liquor_estandar = ms_total_melter / (brix_liquor_estandar / 100.0)

        fuente_15 = cfg['OP_Calentador15_Vapor_Fuente']
        h_15 = cat_vap.get(fuente_15, cat_vap['Vapor_4'])['entalpia']
        recalentador_15_vapor = (flujo_liquor_estandar * 0.85 * (91.4 - 89.6) * 0.001 * 1000.0) / h_15

        cond_cascada_9635 = res['M5']['OUT_Condensados_Tanque9635_th'] * 0.90
        total_9635 = (cond_cascada_9635 + res['M4']['OUT_Calent10_Vapor_th'] + res['M4']['OUT_Calent11_12_Vapor_th'] +
                      res['M4']['OUT_Calent13_Vapor_th'] + res['M3']['OUT_Calent_No9_Vapor_th'] +
                      res['M3']['OUT_Calent_4_Vapor_th'] + res['M3']['OUT_Calent_56_Vapor_th'])
        flash_9635 = total_9635 * 0.02
        neto_9635 = total_9635 - flash_9635

        pkf_2230_1 = res['M3']['OUT_JugoFino_Total_th'] * 0.03
        scrubber_th = 12.00
        intercambiador_3b_2080_1 = max(0.0, neto_9635 - scrubber_th - pkf_2230_1)

        total_9620 = res['M6']['OUT_Vapor3_Demanda_Total_th'] + res['M6']['OUT_Vapor4_Demanda_Total_th'] + recalentador_15_vapor + res['M6']['OUT_SecaderoAzucar_Vapor_th']
        neto_9620 = total_9620 * 0.95

        flujo_total_4605 = neto_9620 + intercambiador_3b_2080_1
        temp_total_4605 = ((neto_9620 * 59.0) + (intercambiador_3b_2080_1 * 86.0)) / flujo_total_4605 if flujo_total_4605 > 0 else 81.76

        res['M7'] = {
            'IN_Mod7_JarabeEvap_th': round(flujo_jarabe, 2),
            'IN_Mod7_AzucarB_th': round(azucar_b_fundicion, 2),
            'IN_Mod7_PolvoSecadero_th': round(polvo_secadero, 2),
            'OUT_Refundicion_MasaSecaTotal_th': round(ms_total_melter, 2),
            'OUT_StandardLiquor_Flujo_th': round(flujo_liquor_estandar, 2),
            'OUT_StandardLiquor_Brix_pct': round(brix_liquor_estandar, 2),
            'OUT_StandardLiquor_Pureza_pct': round(pureza_base + 2.1, 2),
            'OUT_StandardLiquor_Temp_C': 91.40,
            'OUT_Melter_Recalentador15_Vapor_th': round(recalentador_15_vapor, 2),
            'OUT_Deposito9635_FlujoTotal_th': round(total_9635, 2),
            'OUT_Deposito9635_VaporFlashV6_th': round(flash_9635, 2),
            'OUT_Deposito9635_FlujoNetoLiquido_th': round(neto_9635, 2),
            'OUT_Intercambiador3B_2080_1_Calculado_th': round(intercambiador_3b_2080_1, 2),
            'OUT_AguaLavadoFiltros_th': round(pkf_2230_1, 2),
            'OUT_Deposito9620_FlujoTotal_th': round(total_9620, 2),
            'OUT_Deposito9620_FlujoNetoLiquido_th': round(neto_9620, 2),
            'OUT_Deposito4056_4605_Flujo_th': round(flujo_total_4605, 2),
            'OUT_Deposito4056_4605_Temp_C': round(temp_total_4605, 2),
            'OUT_Condensados_Totales_th': round(total_9635 + total_9620 + res['M5']['OUT_Condensados_Calderas4056_th'], 2)
        }

        # MÓDULO 8
        pulpa_humeda_th = res['M1']['OUT_DifPren_PulpaPrensada_Secado_th']
        ms_pulpa_pct = cfg['OP_DifPren_MS_PulpaPrensada_pct']
        ms_pulpa_th = pulpa_humeda_th * (ms_pulpa_pct / 100.0)

        humedad_pellet_pct = cfg['OP_Pulpa_HumedadPellet_pct']
        ms_pellet_pct = 100.0 - humedad_pellet_pct
        pellet_producido_th = ms_pulpa_th / (ms_pellet_pct / 100.0)
        agua_evap_sec = pulpa_humeda_th - pellet_producido_th

        calor_sec_kwh = agua_evap_sec * 1000.0 * 1.05
        pci_gas = cfg['OP_SecaderoPulpa_PCI_Gas_kWh_m3']
        rend_sec = cfg['OP_SecaderoPulpa_RendimientoTérmico_pct'] / 100.0
        gas_m3h = calor_sec_kwh / (pci_gas * rend_sec)

        v_vivo_calderas = res['M5']['OUT_VaporCalderas_1erEfecto_th'] + res['M4']['OUT_Calent14_Vapor_th'] + (0.05 * molienda)
        pot_elec_mw = (v_vivo_calderas * cfg['OP_Turbina_ConsumoEspecifico_kWh_tVapor']) / 1000.0

        res['M8'] = {
            'OUT_PulpaPrensada_Entrada_th': round(pulpa_humeda_th, 2),
            'OUT_PelletPulpa_Producido_th': round(pellet_producido_th, 2),
            'OUT_SecaderoPulpa_AguaEvaporada_th': round(agua_evap_sec, 2),
            'OUT_SecaderoPulpa_GasNatural_m3h': round(gas_m3h, 2),
            'OUT_Caldera_VaporVivoTotal_th': round(v_vivo_calderas, 2),
            'OUT_Cogeneracion_PotenciaElectrica_MW': round(pot_elec_mw, 2),
            'OUT_KPI_VaporSobreRemolacha_pct': round((v_vivo_calderas / molienda) * 100.0, 2),
            'OUT_KPI_RendimientoAzucar_pct': round((azucar_comercial / molienda) * 100.0, 2)
        }

        return res

# ====================================================================
# DISEÑO DE LA APLICACIÓN WEB EN STREAMLIT
# ====================================================================
st.title("🏭 Simulador Proceso Azucarera ACOR 2026")
st.markdown("Ajusta los parámetros operativos y de selección de fuentes de vapor en la barra lateral para recalcular dinámicamente todo el balance.")

st.sidebar.header("⚙️ PARÁMETROS GENERALES & MATERIA PRIMA")
in_molienda = st.sidebar.slider("Molienda t/h", 300.0, 800.0, 550.0, 5.0)
in_riqueza = st.sidebar.slider("Riqueza Remolacha (%)", 12.0, 22.0, 17.4, 0.1)
in_pureza = st.sidebar.slider("Pureza Agrícola (%)", 85.0, 95.0, 90.4, 0.1)
in_marc = st.sidebar.slider("Marco Remolacha (%)", 3.0, 7.0, 4.5, 0.1)
op_ratio_ext = st.sidebar.slider("Draft", 1.0, 1.3, 1.11, 0.01)
op_cao_pct = st.sidebar.slider("OP_Depuracion_CaO_pct_remolacha (%)", 0.8, 2.0, 1.28, 0.01)
op_evap_brix_obj = st.sidebar.slider("OP_Evaporacion_BrixSalida_objetivo_pct (%)", 60.0, 75.0, 69.4, 0.1)

# SELECCIÓN DINÁMICA DE FUENTES DE VAPOR POR EQUIPO EN BARRA LATERAL
st.sidebar.header("🔌 SELECCIÓN DE VAPOR / ENERGÍA POR EQUIPO")
with st.sidebar.expander("Difusión (Int 17, 18+19, 20)", expanded=False):
    f_v17 = st.selectbox("Intercambiador 17", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_5'))
    f_v18 = st.selectbox("Intercambiadores 18+19", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_V5_A609'))
    f_v20 = st.selectbox("Intercambiador 20", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_V5_A609'))

with st.sidebar.expander("Calentamiento Crudo (Int 00 al 3A)", expanded=False):
    f_v00 = st.selectbox("Intercambiador 00", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vahos_Tachas'))
    f_v0 = st.selectbox("Intercambiador 0", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vahos_Tachas'))
    f_v1 = st.selectbox("Intercambiador 1", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vahos_Tachas'))
    f_v2 = st.selectbox("Intercambiador 2", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vahos_Tachas'))
    f_v3 = st.selectbox("Intercambiador 3", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_6'))
    f_v3a = st.selectbox("Intercambiador 3A", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Condensado_A609_Sensible'))

with st.sidebar.expander("Tren Térmico Depuración (3B al 9)", expanded=False):
    f_v3b = st.selectbox("Calentador 3B", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Condensados'))
    f_v4 = st.selectbox("Calentador 4", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_6'))
    f_v56 = st.selectbox("Calentadores 5+6", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_5'))
    f_v7 = st.selectbox("Calentador 7", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_4'))
    f_v8 = st.selectbox("Calentador 8", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_5'))
    f_v9 = st.selectbox("Calentador 9", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_3'))

with st.sidebar.expander("Thin Juice & Melter (Calentadores 10 al 15)", expanded=False):
    f_v10 = st.selectbox("Recalentador 10", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_3'))
    f_v11_12 = st.selectbox("Recalentadores 11+12", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_2'))
    f_v13 = st.selectbox("Recalentador 13", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_1'))
    f_v14 = st.selectbox("Recalentador 14", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_Escape'))
    f_v15 = st.selectbox("Recalentador 15 (Melter)", LISTA_TIPOS_VAPOR, index=LISTA_TIPOS_VAPOR.index('Vapor_4'))

# Consolidado de configuración para la simulación
config_usuario = {
    'IN_Molienda_th': in_molienda,
    'IN_Riqueza_Remolacha_pct': in_riqueza,
    'IN_Pureza_Agricola_pct': in_pureza,
    'IN_Marc_Fibra_pct': in_marc,
    'OP_DifPren_Ratio_Extraccion': op_ratio_ext,
    'OP_Depuracion_CaO_pct_remolacha': op_cao_pct,
    'OP_Evaporacion_BrixSalida_objetivo_pct': op_evap_brix_obj,
    'OP_DifPren_Int17_FuenteVapor': f_v17,
    'OP_DifPren_Int18_19_FuenteVapor': f_v18,
    'OP_DifPren_Int20_FuenteVapor': f_v20,
    'OP_Cal_Verde_Int00_FuenteVapor': f_v00,
    'OP_Cal_Verde_Int0_FuenteVapor': f_v0,
    'OP_Cal_Verde_Int1_FuenteVapor': f_v1,
    'OP_Cal_Verde_Int2_FuenteVapor': f_v2,
    'OP_Cal_Verde_Int3_FuenteVapor': f_v3,
    'OP_Cal_Verde_Int3a_FuenteVapor': f_v3a,
    'OP_Vapor_Calentador_3B': f_v3b,
    'OP_Vapor_Calentador_4': f_v4,
    'OP_Vapor_Calentador_56': f_v56,
    'OP_Vapor_Calentador_7': f_v7,
    'OP_Vapor_Calentador_No8': f_v8,
    'OP_Vapor_Calentador_No9': f_v9,
    'OP_Vapor_Calentador10': f_v10,
    'OP_Vapor_Calentador11_12': f_v11_12,
    'OP_Vapor_Calentador13': f_v13,
    'OP_Vapor_Calentador14': f_v14,
    'OP_Calentador15_Vapor_Fuente': f_v15
}

planta = PlantaAzucareraCompleta(config_usuario)
resultados = planta.simular()

# Pestañas de visualización en Streamlit
tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8, tab9 = st.tabs([
    "M1: Difusión", "M2: Cal. Verde", "M3: Depuración", "M4: Jugo Fino",
    "M5: Evaporación", "M6: Cocimiento", "M7: Condensados", "M8: Energía", "📄 REPORTE GLOBAL"
])

def render_tab_data(mod_key, titulo):
    st.subheader(f"📊 {titulo}")
    df = pd.DataFrame(list(resultados[mod_key].items()), columns=['Variable Output del Balance', 'Valor Calculado'])
    st.dataframe(df, use_container_width=True, hide_index=True)

with tab1: render_tab_data('M1', 'Módulo 1: Difusiones y Prensas')
with tab2: render_tab_data('M2', 'Módulo 2: Calentamiento de Jugo Verde')
with tab3: render_tab_data('M3', 'Módulo 3: Depuración y Carbonataciones')
with tab4: render_tab_data('M4', 'Módulo 4: Thin Juice Heating')

with tab5:
    st.subheader("📊 Módulo 5: Estación de Evaporación y Balance Térmico")
    m5 = resultados['M5']
    st.markdown(f"""
    * **Vapor de Calderas / Escape necesario para 1º Efecto** : {m5['OUT_VaporCalderas_1erEfecto_th']:,.2f} t/h
    * **Flujo de Jarabe Espeso (Thick Juice)** : {m5['OUT_ThickJuice_Flujo_th']:,.2f} t/h
    * **Brix Objetivo Configurado** : {m5['OUT_ThickJuice_Brix_pct']:,.2f}% Bx
    * **Temperatura Final de Salida** : {m5['OUT_ThickJuice_Temp_C']:,.2f} ºC
    """)
    det = m5['OUT_Detalle_Etapas_Evaporacion']
    for k, d in det.items():
        st.markdown(f"**• {d['Vapor_Tipo']} ({k.upper()}):**")
        st.markdown(f"&nbsp;&nbsp;&nbsp;&nbsp;[JUGO SALIDA] - Flujo: {d['Jugo_Flujo_th']} t/h | Brix: {d['Jugo_Brix_pct']}% Bx | Tª: {d['Jugo_Temp_C']} ºC")
        st.markdown(f"&nbsp;&nbsp;&nbsp;&nbsp;[OFERTA VAPOR] - Generado Evap: {d['Vapor_Generado_th']} t/h | Vapor Flash: {d['Vapor_Flash_th']} t/h | Total: {d['Vapor_Total_th']} t/h | Tª: {d['Vapor_Temp_C']} ºC")

    df_m5 = pd.DataFrame(list(m5.items()), columns=['Variable Output', 'Valor'])
    st.dataframe(df_m5, use_container_width=True, hide_index=True)

with tab6: render_tab_data('M6', 'Módulo 6: Cocimiento y Cristalización')
with tab7: render_tab_data('M7', 'Módulo 7: Refundición y Condensados')
with tab8: render_tab_data('M8', 'Módulo 8: Secadero de Pulpa y Energía')

with tab9:
    st.subheader("📄 Consolidado de Reportes Integrados (M1 al M8)")
    reporte_completo = ""
    for k in ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8']:
        reporte_completo += f"========================================================================\n"
        reporte_completo += f" 📊 REPORTE DE SALIDAS: {k}\n"
        reporte_completo += f"========================================================================\n"
        for var, val in resultados[k].items():
            if isinstance(val, (int, float)):
                reporte_completo += f"  • {var:<52} : {val:>15,.2f}\n"
            else:
                reporte_completo += f"  • {var:<52} : {str(val):>15}\n"
        reporte_completo += "\n"
    st.text_area("Texto de Auditoría Maestro", reporte_completo, height=600)