# -*- coding: utf-8 -*-
"""codigo app rev2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5DWX7E1Yk7vHd-bC0RrIQiPM1rkCjDG
"""

import streamlit as st
import pandas as pd
import numpy as np

# ====================================================================
# CONFIGURACIÓN DE PÁGINA STREAMLIT
# ====================================================================
st.set_page_config(
    page_title="Gemelo Digital ACOR 2026 | Termodinámica Pura",
    page_icon="🏭",
    layout="wide"
)

# ====================================================================
# CATÁLOGOS MAESTROS Y PROPIEDADES TERMODINÁMICAS
# ====================================================================
CATALOGO_VAPORES = {
    'Vapor_Escape': {'entalpia': 502.2},
    'Vapor_1erEfecto': {'entalpia': 521.5},
    'Vapor_2doEfecto': {'entalpia': 525.0},
    'Vapor_3erEfecto': {'entalpia': 528.0},
    'Vapor_4toEfecto': {'entalpia': 533.0},
    'Vapor_5toEfecto': {'entalpia': 536.0},
    'Vapor_6toEfecto': {'entalpia': 542.0},
    'Vapor_Tachas_57C': {'entalpia': 565.0},
    'Condensados_Deposito9635': {'entalpia': 94.0}
}

# ====================================================================
# MOTOR MATEMÁTICO: BALANCES DE MASA, ENERGÍA Y SJM
# ====================================================================
class PlantaAzucareraCompleta:
    def __init__(self, config):
        self.config = config
        self.cat_vap = CATALOGO_VAPORES
        self.resultados = {}

    def mod_1_difusiones(self):
        c = self.config
        out = {}

        molienda = float(c['IN_Molienda_th'])
        flujo_jugo = molienda * float(c['OP_DifPren_Ratio_Extraccion'])

        fibra_seca_th = molienda * (float(c['IN_Marc_Fibra_pct']) / 100.0)
        pulpa_prensada_th = fibra_seca_th / (float(c['OP_DifPren_MS_PulpaPrensada_pct']) / 100.0)

        f_agua_pren = molienda * (float(c['OP_DifPren_Ratio_AguaPrensas_pct']) / 100.0)
        f_recirc = molienda * (float(c['OP_DifPren_Ratio_Recirculacion_pct']) / 100.0)
        f_desesp = molienda * (float(c['OP_DifPren_Ratio_Desespumador_pct']) / 100.0)

        dt_17 = max(0.0, float(c['OP_DifPren_Int17_TempOut_C']) - float(c['OP_DifPren_Int17_TempIn_C']))
        out['OUT_Calentador17_Vapor_th'] = (f_agua_pren * 1.0 * dt_17) / self.cat_vap['Vapor_5toEfecto']['entalpia']

        dt_18_19 = max(0.0, float(c['OP_DifPren_Int18_19_TempOut_C']) - float(c['OP_DifPren_Int18_19_TempIn_C']))
        out['OUT_Calentador18_19_Vapor_th'] = (f_recirc * 1.0 * dt_18_19) / self.cat_vap['Vapor_5toEfecto']['entalpia']

        dt_20 = max(0.0, float(c['OP_DifPren_Int20_TempOut_C']) - float(c['OP_DifPren_Int20_TempIn_C']))
        out['OUT_Calentador20_Vapor_th'] = (f_desesp * 1.0 * dt_20) / self.cat_vap['Vapor_5toEfecto']['entalpia']

        out.update({
            'OUT_CanaProcesada_th': molienda,
            'OUT_DifPren_JugoCrudo_Flujo_th': flujo_jugo,
            'OUT_DifPren_JugoCrudo_DS_pct': 17.16,
            'OUT_DifPren_JugoCrudo_Pureza_pct': float(c['IN_Pureza_Agricola_pct']),
            'OUT_DifPren_JugoCrudo_Temp_C': float(c['OP_DifPren_Temp_JugoCrudo_C']),
            'OUT_DifPren_PulpaPrensada_Secado_th': pulpa_prensada_th,
            'OUT_DifPren_AguaPrensas_Flujo_th': f_agua_pren,
            'OUT_DifPren_Recirculacion_Flujo_th': f_recirc,
            'OUT_DifPren_Desespumador_Flujo_th': f_desesp,
            'OUT_DifPren_Int18_19_Condensado_th': out['OUT_Calentador18_19_Vapor_th'],
            'OUT_DifPren_Int20_Condensado_th': out['OUT_Calentador20_Vapor_th']
        })
        return out

    def mod_2_calentamiento_crudo(self, m1):
        c = self.config
        out = {}
        flujo_jugo = float(m1['OUT_DifPren_JugoCrudo_Flujo_th'])
        ds_jugo = float(m1['OUT_DifPren_JugoCrudo_DS_pct'])
        t_in = float(m1['OUT_DifPren_JugoCrudo_Temp_C'])

        cp_jugo = 1.0 - (0.005 * ds_jugo)

        rutas_vapor = {
            '00': 'Vapor_Tachas_57C', '0': 'Vapor_Escape',
            '1': 'Vapor_Escape', '2': 'Vapor_Escape', '3': 'Vapor_6toEfecto'
        }

        for eq in ['00', '0', '1', '2', '3']:
            t_out = float(c[f'OP_CalCrudo_Int{eq}_TempOut_C'])
            dt = max(0.0, t_out - t_in)
            fuente = rutas_vapor[eq]
            out[f'OUT_Calentador{eq}_Vapor_th'] = (flujo_jugo * cp_jugo * dt) / self.cat_vap[fuente]['entalpia']
            t_in = t_out

        out['OUT_CalCrudo_TempFinal_C'] = float(c.get('OP_CalCrudo_Int3a_TempOut_C', 59.0))
        out['OUT_CalCrudo_FlujoSalida_th'] = flujo_jugo
        out['OUT_CalCrudo_DS_Salida_pct'] = ds_jugo
        return out

    def mod_3_depuracion(self, m1, m2, m8):
        c = self.config
        out = {}
        molienda = float(m1['OUT_CanaProcesada_th'])
        f_escala = molienda / 445.0

        flujo_jugo_entrada = float(m2['OUT_CalCrudo_FlujoSalida_th'])
        brix_entrada = float(m2['OUT_CalCrudo_DS_Salida_pct'])
        pureza_base = float(c['IN_Pureza_Agricola_pct'])

        cp_jugo = 0.94
        cp_agua = 1.00

        lodos_2do = 27.17 * f_escala
        t_CaO_total = molienda * (float(c['OP_Depuracion_CaO_pct_remolacha']) / 100.0)
        flujo_lechada_total = t_CaO_total / 0.1444
        lechada_preencalado = flujo_lechada_total * 0.24
        lechada_encalado_frio = flujo_lechada_total * 0.76

        alc_1ra_caida = max(0.0, float(c['OP_1raCarb_AlcalinidadEntrada_gh']) - float(c['OP_1raCarb_AlcalinidadSalida']))
        co2_1 = (flujo_jugo_entrada * alc_1ra_caida * (44.0/56.0)) / 1000.0
        caco3_1ra = (flujo_jugo_entrada * alc_1ra_caida / 1000.0) * (100.0/56.0)

        alc_2da_caida = max(0.0, float(c['OP_1raCarb_AlcalinidadSalida']) - float(c['OP_2daCarb_AlcalinidadSalida']))
        cao_reacc_2da = (flujo_jugo_entrada * alc_2da_caida) / 1000.0
        co2_2 = cao_reacc_2da * (44.0/56.0)

        azucar_corefin = float(c['OP_AzucarCorefin_th']) * f_escala

        flujo_etapa_1 = flujo_jugo_entrada + lodos_2do + lechada_preencalado
        flujo_etapa_2 = flujo_etapa_1 + azucar_corefin + lechada_encalado_frio

        t_in_3b = float(c['OP_Calent_3B_TempEntrada_C'])
        t_out_3b = float(c['OP_Calent_3B_TempSalida_C'])
        carga_3b_Mcal = flujo_etapa_2 * cp_jugo * max(0.0, t_out_3b - t_in_3b)

        caudal_3b_condensados = float(m8.get('OUT_Intercambiador3B_2080_1_Calculado_th', 266.0 * f_escala))
        t_cond_in_3b = float(m8.get('OUT_Deposito9635_TempSalida_C', 94.0))
        t_cond_out_3b = t_cond_in_3b - (carga_3b_Mcal / (caudal_3b_condensados * cp_agua)) if caudal_3b_condensados > 0 else t_cond_in_3b

        t_out_4 = float(c['OP_Calent_4_TempSalida_C'])
        out['OUT_Calentador4_Vapor_th'] = (flujo_etapa_2 * cp_jugo * max(0.0, t_out_4 - t_out_3b)) / self.cat_vap['Vapor_6toEfecto']['entalpia']
        t_out_56 = float(c['OP_Calent_56_TempSalida_C'])
        out['OUT_Calentador5_6_Vapor_th'] = (flujo_etapa_2 * cp_jugo * max(0.0, t_out_56 - t_out_4)) / self.cat_vap['Vapor_5toEfecto']['entalpia']
        t_out_7 = float(c['OP_Calent_7_TempSalida_C'])
        out['OUT_Calentador7_Vapor_th'] = (flujo_etapa_2 * cp_jugo * max(0.0, t_out_7 - t_out_56)) / self.cat_vap['Vapor_4toEfecto']['entalpia']

        evap_agua_1ra = 1.75 * f_escala
        vap_5_1ra_th = 0.29 * f_escala
        flujo_etapa_3 = flujo_etapa_2 + co2_1 + vap_5_1ra_th - evap_agua_1ra
        t_out_1ra_carb = t_out_7 - float(c['OP_Enfriamiento_1raCarb_C'])

        barros_1ro = 55.90 * f_escala
        jugo_claro = flujo_etapa_3 - barros_1ro

        t_out_no8 = float(c['OP_Calent_No8_TempSalida_C'])
        out['OUT_Calentador8_Vapor_th'] = (jugo_claro * cp_jugo * max(0.0, t_out_no8 - t_out_1ra_carb)) / self.cat_vap['Vapor_5toEfecto']['entalpia']
        t_out_1ra_filt = t_out_no8 - float(c['OP_Enfriamiento_1raFiltracion_C'])

        filtrato_pkf = 15.90 * f_escala
        azucar_baja = 0.54 * f_escala

        flujo_etapa_4 = jugo_claro + filtrato_pkf + azucar_baja

        t_out_no9 = float(c['OP_Calent_No9_TempSalida_C'])
        out['OUT_Calentador9_Vapor_th'] = (flujo_etapa_4 * cp_jugo * max(0.0, t_out_no9 - t_out_1ra_filt)) / self.cat_vap['Vapor_3erEfecto']['entalpia']
        t_out_2da_carb = t_out_no9 - float(c['OP_Enfriamiento_2daCarb_C'])

        evap_agua_2da = 0.80 * f_escala
        flujo_etapa_5 = flujo_etapa_4 + co2_2 - evap_agua_2da

        flujo_jugo_fino_total = flujo_etapa_5 - lodos_2do
        perdidas_indef = molienda * 0.0016
        flujo_jugo_fino_melting = flujo_jugo_fino_total * (float(c['OP_JugoFino_DestinoMelting_pct']) / 100.0)

        flujo_jugo_fino_mod4 = max(0.1, flujo_jugo_fino_total - flujo_jugo_fino_melting - perdidas_indef)

        ms_jugo_crudo = flujo_jugo_entrada * (brix_entrada / 100.0)
        ms_barros_1ro = barros_1ro * 0.20
        ms_jugo_fino_real = ms_jugo_crudo + azucar_corefin - perdidas_indef - (ms_barros_1ro * 0.1)
        brix_fino_real = (ms_jugo_fino_real / flujo_jugo_fino_total) * 100.0 if flujo_jugo_fino_total > 0 else 18.40

        out.update({
            'OUT_Depuracion_CaO_Activo_th': t_CaO_total,
            'OUT_1raCarb_Salida_th': flujo_etapa_3,
            'OUT_2daCarb_Salida_th': flujo_etapa_5,
            'OUT_2daFiltracion_LodosRecirc_th': lodos_2do,
            'OUT_JugoFino_Total_th': flujo_jugo_fino_total,
            'OUT_JugoFino_Brix_pct': brix_fino_real,
            'OUT_JugoFino_Temp_C': t_out_2da_carb,
            'OUT_JugoFino_ParaModulo4_Calentamiento_th': flujo_jugo_fino_mod4,
            'OUT_Calent_3B_TempSalidaCondensado_C': t_cond_out_3b,
            'OUT_Calentador4_Vapor_th': out['OUT_Calentador4_Vapor_th'],
            'OUT_Calentador5_6_Vapor_th': out['OUT_Calentador5_6_Vapor_th'],
            'OUT_Calentador7_Vapor_th': out['OUT_Calentador7_Vapor_th'],
            'OUT_Calentador8_Vapor_th': out['OUT_Calentador8_Vapor_th'],
            'OUT_Calentador9_Vapor_th': out['OUT_Calentador9_Vapor_th']
        })
        return out

    def mod_4_calentamiento_jugo_fino(self, m3):
        c = self.config
        out = {}
        cp_jugo = 0.96
        flujo_jugo_fino = float(m3.get('OUT_JugoFino_ParaModulo4_Calentamiento_th', 500.0))
        temp_entrada = float(m3.get('OUT_JugoFino_Temp_C', 87.3))

        t_10 = float(c['OP_Calentador10_TempSalida_C'])
        out['OUT_Calentador10_Vapor_th'] = (flujo_jugo_fino * cp_jugo * max(0.0, t_10 - temp_entrada)) / self.cat_vap['Vapor_3erEfecto']['entalpia']

        t_11_12 = float(c['OP_Calentador11_12_TempSalida_C'])
        v11_12 = (flujo_jugo_fino * cp_jugo * max(0.0, t_11_12 - t_10)) / self.cat_vap['Vapor_2doEfecto']['entalpia']
        out['OUT_Calentador11_Vapor_th'] = v11_12 * 0.4
        out['OUT_Calentador12_Vapor_th'] = v11_12 * 0.6

        t_13 = float(c['OP_Calentador13_TempSalida_C'])
        out['OUT_Calentador13_Vapor_th'] = (flujo_jugo_fino * cp_jugo * max(0.0, t_13 - t_11_12)) / self.cat_vap['Vapor_1erEfecto']['entalpia']

        t_14 = float(c['OP_Calentador14_TempSalida_C'])
        out['OUT_Calentador14_Vapor_th'] = (flujo_jugo_fino * cp_jugo * max(0.0, t_14 - t_13)) / self.cat_vap['Vapor_Escape']['entalpia']

        out['OUT_JugoFinoCalentado_Flujo_th'] = flujo_jugo_fino
        out['OUT_JugoFinoCalentado_Temp_C'] = t_14
        return out

    # ====================================================================
    # NUEVO SOLVER CONJUNTO MÓDULO 6 Y 7 (Iteración Interna Matemática)
    # ====================================================================
    def mod_6_7_cocimiento_y_refundicion(self, m1, m3, m5):
        c = self.config
        out6 = {}
        out7 = {}

        flujo_jarabe = float(m5.get('OUT_ThickJuice_Flujo_th', 133.39))
        brix_jarabe = float(m5.get('OUT_ThickJuice_Brix_pct', 69.40))
        S_TJ = flujo_jarabe * (brix_jarabe / 100.0)

        flujo_jf_melt = float(m3.get('OUT_JugoFino_Total_th', 505.2)) * (float(c['OP_JugoFino_DestinoMelting_pct'])/100.0)
        brix_jf = float(m3.get('OUT_JugoFino_Brix_pct', 18.40))
        S_JF = flujo_jf_melt * (brix_jf / 100.0)

        # Purezas analíticas del proceso
        P_TJ = 91.60; P_JF = 91.60
        P_A = 99.80; P_B = 98.70; P_C = 96.70
        P_GA = 83.70; P_GB = 76.20; P_Mol = 57.20

        brix_a = float(c['OP_Cocimiento_BrixMasaA_pct'])
        brix_b = float(c['OP_Cocimiento_BrixMasaB_pct'])
        brix_c = float(c['OP_Cocimiento_BrixMasaC_pct'])
        brix_SL_target = 73.90 # Fijo por ACOR para evitar colapso de agua

        # Variables de Recirculación
        S_B_recycle = 0.0
        S_C_recycle = 0.0
        S_Dust_recycle = 0.0

        # BUCLE SJM MATEMÁTICO (Simula el equilibrio estacionario del Melter y Tachas)
        for _ in range(20):
            # 1. MELTER (Módulo 7)
            S_SL = S_TJ + S_JF + S_B_recycle + S_C_recycle + S_Dust_recycle
            # Mezcla ponderada de purezas
            if S_SL > 0:
                P_SL = (S_TJ*P_TJ + S_JF*P_JF + S_B_recycle*P_B + S_C_recycle*P_C + S_Dust_recycle*P_A) / S_SL
            else:
                P_SL = 93.50

            F_SL = S_SL / (brix_SL_target / 100.0)

            # 2. TACHAS A (Módulo 6)
            Yield_A = max(0.0, (P_SL - P_GA) / (P_A - P_GA)) if P_A != P_GA else 0.0
            S_A = S_SL * Yield_A
            S_GA = S_SL - S_A

            # 3. TACHAS B
            Yield_B = max(0.0, (P_GA - P_GB) / (P_B - P_GB)) if P_B != P_GB else 0.0
            S_B_new = S_GA * Yield_B
            S_GB = S_GA - S_B_new

            # 4. TACHAS C
            Yield_C = max(0.0, (P_GB - P_Mol) / (P_C - P_Mol)) if P_C != P_Mol else 0.0
            S_C_new = S_GB * Yield_C
            S_Mol = S_GB - S_C_new

            # Separación Polvo vs Comercial
            S_Dust_new = S_A * 0.058 # 5.8% histórico ACOR

            # Update Reciclos
            S_B_recycle = S_B_new
            S_C_recycle = S_C_new
            S_Dust_recycle = S_Dust_new

        # RESULTADOS CONVERGIDOS
        azucar_comercial = (S_A - S_Dust_recycle) / (P_A / 100.0)

        # Consumos de Vapor Físicos basados en agua evaporada
        Masa_A = S_SL / (brix_a / 100.0) if brix_a > 0 else 0.0
        vapor_tacha_a = max(0.0, F_SL - Masa_A)

        F_GA = S_GA / 0.787
        Masa_B = S_GA / (brix_b / 100.0) if brix_b > 0 else 0.0
        vapor_tacha_b = max(0.0, F_GA - Masa_B)

        F_GB = S_GB / 0.846
        Masa_C = S_GB / (brix_c / 100.0) if brix_c > 0 else 0.0
        vapor_tacha_c = max(0.0, F_GB - Masa_C)

        # Consumo de vapor del Melter (Módulo 7)
        F_B_recycle = S_B_recycle / (P_B/100.0)
        F_C_recycle = S_C_recycle / (P_C/100.0)
        F_Dust_recycle = S_Dust_recycle / (P_A/100.0)

        flujo_total_entrante_th = flujo_jarabe + F_B_recycle + F_C_recycle + F_Dust_recycle + flujo_jf_melt
        calor_sensible_Mcal_h = flujo_total_entrante_th * 0.85 * max(0.0, 91.4 - 89.6)
        fuente_vapor_15 = str(c.get('OP_Calentador15_Vapor_Fuente', 'Vapor_4toEfecto'))
        vapor_requerido_15 = calor_sensible_Mcal_h / self.cat_vap[fuente_vapor_15]['entalpia']

        out6.update({
            'OUT_AzucarComercial_Silo_th': azucar_comercial,
            'OUT_PolvoSecadero_Recuperado_th': F_Dust_recycle,
            'OUT_AzucarB_Fundicion_th': F_B_recycle,
            'OUT_AzucarB_Polarizacion_pct': P_B,
            'OUT_Vapor4_Demanda_CristalizacionA_th': vapor_tacha_a,
            'OUT_Vapor3_Demanda_CristalizacionB_th': vapor_tacha_b,
            'OUT_Vapor4_Demanda_CristalizacionC_th': vapor_tacha_c,
            'OUT_Vapor4_Demanda_Total_th': vapor_tacha_a + vapor_tacha_c,
            'OUT_Vapor3_Demanda_Total_th': vapor_tacha_b,
            'OUT_SecaderoAzucar_Vapor_th': azucar_comercial * 0.0245,
            'OUT_MelazaFinal_th': S_Mol / 0.797
        })

        out7.update({
            'OUT_Refundicion_MasaSecaTotal_th': S_SL,
            'OUT_StandardLiquor_Flujo_th': F_SL,
            'OUT_StandardLiquor_Brix_pct': brix_SL_target,
            'OUT_StandardLiquor_Temp_C': 91.4,
            'OUT_Calentador15_VaporConsumo_th': vapor_requerido_15,
            'OUT_Mod7_Resumen_Vapores_th': {fuente_vapor_15: vapor_requerido_15}
        })

        return out6, out7

    def mod_5_evaporacion(self, m4, m3, m6, m7, m1, m2):
        c = self.config
        out = {}

        flujo_entrada = float(m4.get('OUT_JugoFinoCalentado_Flujo_th', 500.0))
        temp_entrada = float(m4.get('OUT_JugoFinoCalentado_Temp_C', 123.8))
        brix_entrada = float(m3.get('OUT_JugoFino_Brix_pct', 18.40))

        if brix_entrada <= 0 or brix_entrada > 40: brix_entrada = 18.40

        masa_seca_th = flujo_entrada * (brix_entrada / 100.0)
        brix_salida_obj = float(c['OP_Evaporacion_BrixSalida_objetivo_pct'])
        flujo_jarabe_th = masa_seca_th / (brix_salida_obj / 100.0) if brix_salida_obj > 0 else 0.0

        W = max(1.0, flujo_entrada - flujo_jarabe_th)

        out['OUT_ThickJuice_Flujo_th'] = flujo_jarabe_th
        out['OUT_Evaporacion_AguaTotalEvaporada_th'] = W

        temp_vap = [131.0, 126.4, 120.2, 112.4, 106.5, 94.0]
        temp_jugo = [131.6, 127.3, 122.2, 116.5, 110.8, 99.5]
        L = [521.5, 525.0, 528.0, 533.0, 536.0, 542.0]
        cp_jugo = 0.94
        cp_agua = 1.00
        SANGRIA = 0.30

        dem_m7 = m7.get('OUT_Mod7_Resumen_Vapores_th', {})
        D = [0.0]*6

        # ASIGNACIÓN DE VAPORES: A=V4, B=V3, C=V4
        D[0] = float(m4.get('OUT_Calentador13_Vapor_th', 0.0)) + float(dem_m7.get('Vapor_1erEfecto', 0.0)) + SANGRIA
        D[1] = float(m4.get('OUT_Calentador11_Vapor_th', 0.0)) + float(m4.get('OUT_Calentador12_Vapor_th', 0.0)) + float(dem_m7.get('Vapor_2doEfecto', 0.0)) + SANGRIA
        D[2] = float(m4.get('OUT_Calentador10_Vapor_th', 0.0)) + float(m3.get('OUT_Calentador9_Vapor_th', 0.0)) + float(m6.get('OUT_Vapor3_Demanda_CristalizacionB_th', 0.0)) + float(dem_m7.get('Vapor_3erEfecto', 0.0)) + SANGRIA
        D[3] = float(m3.get('OUT_Calentador7_Vapor_th', 0.0)) + float(m6.get('OUT_Vapor4_Demanda_CristalizacionA_th', 0.0)) + float(m6.get('OUT_Vapor4_Demanda_CristalizacionC_th', 0.0)) + float(dem_m7.get('Vapor_4toEfecto', 0.0)) + SANGRIA
        D[4] = float(m3.get('OUT_Calentador5_6_Vapor_th', 0.0)) + float(m3.get('OUT_Calentador8_Vapor_th', 0.0)) + float(m1.get('OUT_Calentador17_Vapor_th', 0.0)) + float(m1.get('OUT_Calentador18_19_Vapor_th', 0.0)) + float(m1.get('OUT_Calentador20_Vapor_th', 0.0)) + (0.29 * (float(c['IN_Molienda_th'])/445.0)) + SANGRIA
        D[5] = float(m2.get('OUT_Calentador00_Vapor_th', 0.0)) + float(m2.get('OUT_Calentador0_Vapor_th', 0.0)) + float(m2.get('OUT_Calentador1_Vapor_th', 0.0)) + float(m2.get('OUT_Calentador2_Vapor_th', 0.0)) + float(m2.get('OUT_Calentador3_Vapor_th', 0.0)) + SANGRIA

        def simular_cascada(E0):
            E = [0.0]*6
            V_tot = [0.0]*6
            Cond = [0.0]*6
            F_j = [0.0]*6
            Flash_c = [0.0]*6
            Flash_j = [0.0]*6

            E[0] = E0
            V_tot[0] = E[0]
            Cond[0] = E[0]
            F_j[0] = max(0.1, flujo_entrada - E[0])

            for i in range(1, 6):
                V_in = max(0.0, V_tot[i-1] - D[i-1])
                Q_cond = V_in * L[i-1]
                Q_j = F_j[i-1] * cp_jugo * max(0.0, temp_jugo[i-1] - temp_jugo[i])

                E[i] = (Q_cond + Q_j) / L[i]
                Flash_j[i] = Q_j / L[i]
                Flash_c[i] = (Cond[i-1] * cp_agua * max(0.0, temp_vap[i-1] - temp_vap[i])) / L[i]

                V_tot[i] = E[i] + Flash_c[i] + Flash_j[i]
                F_j[i] = max(0.1, F_j[i-1] - E[i] - Flash_j[i])

                extr = 5.08 * (W / 369.46) if i == 1 else 0.0
                Cond[i] = max(0.0, Cond[i-1] - extr) + V_in - Flash_c[i]

            W_calc = sum(E) + sum(Flash_j)
            return W_calc, E, V_tot, Cond

        low, high = 0.0, W * 3.0
        for _ in range(100):
            mid = (low + high) / 2.0
            sum_e_calc, E, V_tot, Cond = simular_cascada(mid)
            if sum_e_calc < W:
                low = mid
            else:
                high = mid

        _, E, V_tot, Cond = simular_cascada(mid)

        out['OUT_Condensados_Calderas4056_th'] = float(Cond[0])
        out['OUT_Condensado_CascadaFinal_9635_th'] = float(Cond[5])

        out['OUT_Balance_Vapores_Demanda'] = {
            'Vapor_1erEfecto': float(D[0]), 'Vapor_2doEfecto': float(D[1]), 'Vapor_3erEfecto': float(D[2]),
            'Vapor_4toEfecto': float(D[3]), 'Vapor_5toEfecto': float(D[4]), 'Vapor_6toEfecto': float(D[5])
        }

        out['OUT_Mod5_OfertaTotalVapores_th'] = {
            'Vapor_1erEfecto': float(V_tot[0]), 'Vapor_2doEfecto': float(V_tot[1]), 'Vapor_3erEfecto': float(V_tot[2]),
            'Vapor_4toEfecto': float(V_tot[3]), 'Vapor_5toEfecto': float(V_tot[4]), 'Vapor_6toEfecto': float(V_tot[5])
        }

        out['OUT_Bypass_2Efecto_th'] = max(0.0, float(D[0] - V_tot[0]))
        out['OUT_Bypass_3Efecto_th'] = max(0.0, float(D[1] - V_tot[1]))
        out['OUT_Bypass_4Efecto_th'] = max(0.0, float(D[2] - V_tot[2]))
        out['OUT_Bypass_5Efecto_th'] = max(0.0, float(D[3] - V_tot[3]))

        q_sens = (flujo_entrada * cp_jugo * max(0.0, temp_jugo[0] - temp_entrada))
        q_lat = (E[0] * L[0])
        out['OUT_VaporCalderas_1erEfecto_th'] = float((q_sens + q_lat) / self.cat_vap['Vapor_Escape']['entalpia'])

        return out

    def mod_8_condensados_agua(self, m5, m6, m4, m3, m1, m2, m7):
        out = {}
        c = self.config
        recalentador_15_vapor_th = float(m7.get('OUT_Calentador15_VaporConsumo_th', 0.48))
        cond_cascada_evaporacion = float(m5.get('OUT_Condensado_CascadaFinal_9635_th', 246.50))

        fuentes_9635 = [
            {'nombre': 'Condensado Evaporación Cascado', 'flujo_th': cond_cascada_evaporacion},
            {'nombre': 'Recalentador Nº 7 (M3)', 'flujo_th': float(m3.get('OUT_Calentador7_Vapor_th', 0.0))},
            {'nombre': 'Recalentador Nº 10 (M4)', 'flujo_th': float(m4.get('OUT_Calentador10_Vapor_th', 26.44))},
            {'nombre': 'Recalentador Nº 11 (M4)', 'flujo_th': float(m4.get('OUT_Calentador11_Vapor_th', 1.25))},
            {'nombre': 'Recalentador Nº 12 (M4)', 'flujo_th': float(m4.get('OUT_Calentador12_Vapor_th', 1.92))},
            {'nombre': 'Recalentador Nº 13 (M4)', 'flujo_th': float(m4.get('OUT_Calentador13_Vapor_th', 1.98))},
            {'nombre': 'Calentador Nº 9 (M3)', 'flujo_th': float(m3.get('OUT_Calentador9_Vapor_th', 6.32))},
            {'nombre': 'Calentador Nº 4 (M3)', 'flujo_th': float(m3.get('OUT_Calentador4_Vapor_th', 16.08))},
            {'nombre': 'Calentadores Nº 5+6 (M3)', 'flujo_th': float(m3.get('OUT_Calentador5_6_Vapor_th', 5.32))},
            {'nombre': 'Calentador Nº 8 (M3)', 'flujo_th': float(m3.get('OUT_Calentador8_Vapor_th', 0.29))},
            {'nombre': 'Agua Prensa Difusión Nº 17 (M1)', 'flujo_th': float(m1.get('OUT_Calentador17_Vapor_th', 3.04))},
        ]
        total_9635 = sum(item['flujo_th'] for item in fuentes_9635)
        flash_9635 = total_9635 * 0.02
        neto_liquido_9635 = total_9635 - flash_9635

        scrubber_th = float(m1.get('OUT_CanaProcesada_th', 445.0)) * (12.0 / 445.0)
        intercambiador_3b_2080_1 = max(0.0, neto_liquido_9635 - scrubber_th)

        fuentes_9620 = [
            {'nombre': 'Tachas B', 'flujo_th': float(m6.get('OUT_Vapor3_Demanda_Total_th', 9.84))},
            {'nombre': 'Tachas A y C', 'flujo_th': float(m6.get('OUT_Vapor4_Demanda_Total_th', 38.97))},
            {'nombre': 'Recalentador Nº 15', 'flujo_th': recalentador_15_vapor_th},
            {'nombre': 'Secadero Azúcar', 'flujo_th': float(m6.get('OUT_SecaderoAzucar_Vapor_th', 1.78))},
            {'nombre': 'Int. 18+19 (M1)', 'flujo_th': float(m1.get('OUT_Calentador18_19_Vapor_th', 2.35))},
            {'nombre': 'Int. 20 (M1)', 'flujo_th': float(m1.get('OUT_Calentador20_Vapor_th', 1.83))}
        ]
        total_9620 = sum(item['flujo_th'] for item in fuentes_9620)
        flash_9620 = total_9620 * 0.05
        neto_liquido_9620 = total_9620 - flash_9620

        flujo_total_4605 = neto_liquido_9620 + intercambiador_3b_2080_1

        out.update({
            'OUT_Deposito9635_FlujoTotal_th': total_9635,
            'OUT_Deposito9635_FlujoNetoLiquido_th': neto_liquido_9635,
            'OUT_Intercambiador3B_2080_1_Calculado_th': intercambiador_3b_2080_1,
            'OUT_Deposito9620_FlujoTotal_th': total_9620,
            'OUT_Deposito9620_FlujoNetoLiquido_th': neto_liquido_9620,
            'OUT_Deposito4056_4605_Flujo_th': flujo_total_4605,
            'OUT_Condensados_Totales_th': total_9635 + total_9620 + float(m5.get('OUT_Condensados_Calderas4056_th', 107.73))
        })
        return out

    def mod_9_energia(self, m1, m4, m5, m6):
        c = self.config
        out = {}

        pulpa = float(m1.get('OUT_DifPren_PulpaPrensada_Secado_th', 0.0))
        ms_pulpa_th = pulpa * (float(c['OP_DifPren_MS_PulpaPrensada_pct']) / 100.0)
        pellet = ms_pulpa_th / ((100.0 - float(c['OP_Pulpa_HumedadPellet_pct'])) / 100.0) if c['OP_Pulpa_HumedadPellet_pct'] < 100.0 else 0.0
        agua_evap_sec = max(0.0, pulpa - pellet)

        rend_termico = float(c['OP_SecaderoPulpa_RendimientoTérmico_pct']) / 100.0
        gas_m3h = (agua_evap_sec * 1000.0 * 1.05) / (float(c['OP_SecaderoPulpa_PCI_Gas_kWh_m3']) * rend_termico) if rend_termico > 0.0 else 0.0

        vapor_calderas = float(m5.get('OUT_VaporCalderas_1erEfecto_th', 0.0)) + float(m4.get('OUT_Calentador14_Vapor_th', 0.0)) + (0.05 * float(c['IN_Molienda_th']))
        mw_elec = (vapor_calderas * float(c['OP_Turbina_ConsumoEspecifico_kWh_tVapor'])) / 1000.0

        out.update({
            'OUT_PelletPulpa_Producido_th': pellet,
            'OUT_SecaderoPulpa_AguaEvaporada_th': agua_evap_sec,
            'OUT_SecaderoPulpa_GasNatural_m3h': gas_m3h,
            'OUT_Caldera_VaporVivoTotal_th': vapor_calderas,
            'OUT_Cogeneracion_PotenciaElectrica_MW': mw_elec,
            'OUT_KPI_VaporSobreRemolacha_pct': (vapor_calderas / float(c['IN_Molienda_th'])) * 100.0 if float(c['IN_Molienda_th']) > 0 else 0.0
        })
        return out

    def simular(self):
        m1 = self.mod_1_difusiones()
        m2 = self.mod_2_calentamiento_crudo(m1)
        m8_init = {}
        m3_init = self.mod_3_depuracion(m1, m2, m8_init)
        m4_init = self.mod_4_calentamiento_jugo_fino(m3_init)

        m5_init = {}

        # BUCLE PRINCIPAL DE CASCADA Y CO-CRISTALIZACIÓN
        for _ in range(5):
            m6_init, m7_init = self.mod_6_7_cocimiento_y_refundicion(m1, m3_init, m5_init)
            m5_init = self.mod_5_evaporacion(m4_init, m3_init, m6_init, m7_init, m1, m2)

        m8 = self.mod_8_condensados_agua(m5_init, m6_init, m4_init, m3_init, m1, m2, m7_init)
        m9 = self.mod_9_energia(m1, m4_init, m5_init, m6_init)

        # Casteo riguroso de Python Floats
        for modulo in [m1, m2, m3_init, m4_init, m5_init, m6_init, m7_init, m8, m9]:
            for k, v in modulo.items():
                if isinstance(v, (int, float, np.floating)):
                    modulo[k] = round(float(v), 2)
                elif isinstance(v, dict):
                    for k2, v2 in v.items():
                        if isinstance(v2, (int, float, np.floating)):
                            v[k2] = round(float(v2), 2)

        self.resultados = {'M1': m1, 'M2': m2, 'M3': m3_init, 'M4': m4_init, 'M5': m5_init, 'M6': m6_init, 'M7': m7_init, 'M8': m8, 'M9': m9}
        return self.resultados

# ====================================================================
# DISEÑO DE LA APLICACIÓN WEB EN STREAMLIT
# ====================================================================
st.title("🏭 Simulador Gemelo Digital Planta ACOR 2026")

# Ejecución para extraer métricas de cabecera
config_usuario = {
    'IN_Molienda_th': 445.0, 'IN_Riqueza_Remolacha_pct': 17.4, 'IN_Pureza_Agricola_pct': 90.4,
    'IN_Marc_Fibra_pct': 4.5, 'OP_DifPren_Ratio_Extraccion': 1.11, 'OP_DifPren_MS_PulpaPrensada_pct': 27.5,
    'OP_DifPren_Temp_JugoCrudo_C': 26.0, 'OP_DifPren_Ratio_AguaAporte_pct': 24.93,
    'OP_DifPren_Mezcla_AguaCaliente_pct': 80.0, 'OP_DifPren_Ratio_AguaPrensas_pct': 37.04,
    'OP_DifPren_Ratio_Recirculacion_pct': 165.0, 'OP_DifPren_Ratio_Desespumador_pct': 46.0,
    'OP_DifPren_Int17_TempIn_C': 62.0, 'OP_DifPren_Int17_TempOut_C': 72.0,
    'OP_DifPren_Int18_19_TempIn_C': 71.4, 'OP_DifPren_Int18_19_TempOut_C': 73.3,
    'OP_DifPren_Int20_TempIn_C': 71.4, 'OP_DifPren_Int20_TempOut_C': 76.5,
    'OP_CalCrudo_Int00_TempOut_C': 47.4, 'OP_CalCrudo_Int0_TempOut_C': 48.8, 'OP_CalCrudo_Int1_TempOut_C': 49.1,
    'OP_CalCrudo_Int2_TempOut_C': 49.1, 'OP_CalCrudo_Int3_TempOut_C': 53.8, 'OP_CalCrudo_Int3a_TempOut_C': 59.0,
    'OP_Depuracion_CaO_pct_remolacha': 1.28, 'OP_AzucarCorefin_th': 8.80, 'OP_1raCarb_AlcalinidadEntrada_gh': 2.50,
    'OP_1raCarb_AlcalinidadSalida': 0.90, 'OP_2daCarb_AlcalinidadSalida': 0.27, 'OP_PKF_MS_Barros_pct': 64.9,
    'OP_Calent_3B_TempEntrada_C': 61.4, 'OP_Calent_3B_TempSalida_C': 65.5, 'OP_Calent_4_TempSalida_C': 82.3,
    'OP_Calent_56_TempSalida_C': 87.8, 'OP_Calent_7_TempSalida_C': 87.8, 'OP_Enfriamiento_1raCarb_C': 1.60,
    'OP_Enfriamiento_1raFiltracion_C': 1.00, 'OP_Enfriamiento_2daCarb_C': 4.70, 'OP_Calent_No8_TempSalida_C': 86.2,
    'OP_Calent_No9_TempSalida_C': 92.0, 'OP_JugoFino_DestinoMelting_pct': 0.31,
    'OP_Calentador10_TempSalida_C': 117.3, 'OP_Calentador11_12_TempSalida_C': 121.6, 'OP_Calentador13_TempSalida_C': 123.8, 'OP_Calentador14_TempSalida_C': 123.8,
    'OP_Evaporacion_BrixSalida_objetivo_pct': 69.4,
    'OP_Cocimiento_BrixMasaA_pct': 91.0, 'OP_Cocimiento_BrixMasaB_pct': 94.6, 'OP_Cocimiento_BrixMasaC_pct': 95.3,
    'OP_Calentador15_Vapor_Fuente': 'Vapor_4toEfecto',
    'OP_Pulpa_HumedadPellet_pct': 10.0, 'OP_SecaderoPulpa_PCI_Gas_kWh_m3': 10.50, 'OP_SecaderoPulpa_RendimientoTérmico_pct': 85.0,
    'OP_Turbina_ConsumoEspecifico_kWh_tVapor': 45.0
}

planta_temp = PlantaAzucareraCompleta(config_usuario)
res_temp = planta_temp.simular()

azucar_producida = res_temp['M6']['OUT_AzucarComercial_Silo_th']
rendimiento = (azucar_producida / 445.0) * 100

st.info(f"🏆 **Rendimiento de Fábrica Actual (Azúcar Comercial / Remolacha): {rendimiento:.2f}%**")

# BARRA LATERAL (INPUTS)
st.sidebar.header("⚙️ PARÁMETROS DE ENTRADA")

with st.sidebar.expander("🌱 Materia Prima & Módulo 1 (Difusión)", expanded=False):
    in_molienda = st.slider("Molienda t/h", 300.0, 800.0, 445.0, 5.0)
    in_riqueza = st.slider("Riqueza_Remolacha_pct (%)", 12.0, 22.0, 17.4, 0.1)
    in_pureza = st.slider("Pureza_Agricola_pct (%)", 85.0, 95.0, 90.4, 0.1)
    in_marc = st.slider("Marc_Fibra_pct (%)", 3.0, 7.0, 4.5, 0.1)
    op_ratio_ext = st.slider("Ratio_Extraccion", 1.0, 1.3, 1.11, 0.01)
    op_ms_pulpa = st.slider("MS_PulpaPrensada_pct (%)", 20.0, 35.0, 27.5, 0.5)
    op_temp_crudo = st.slider("Temp_JugoCrudo_C (°C)", 15.0, 40.0, 26.0, 0.5)
    op_ratio_aporte = st.slider("Ratio_AguaAporte_pct (%)", 15.0, 35.0, 24.93, 0.1)
    op_mezcla_caliente = st.slider("Mezcla_AguaCaliente_pct (%)", 50.0, 100.0, 80.0, 1.0)
    op_ratio_prensas = st.slider("Ratio_AguaPrensas_pct (%)", 20.0, 50.0, 37.04, 0.1)
    op_ratio_recirc = st.slider("Ratio_Recirculacion_pct (%)", 100.0, 200.0, 165.0, 1.0)
    op_ratio_desesp = st.slider("Ratio_Desespumador_pct (%)", 20.0, 70.0, 46.0, 1.0)
    op_int17_tin = st.number_input("Int17_TempIn_C (°C)", value=62.0)
    op_int17_tout = st.number_input("Int17_TempOut_C (°C)", value=72.0)
    op_int18_tin = st.number_input("Int18_19_TempIn_C (°C)", value=71.4)
    op_int18_tout = st.number_input("Int18_19_TempOut_C (°C)", value=73.3)
    op_int20_tin = st.number_input("Int20_TempIn_C (°C)", value=71.4)
    op_int20_tout = st.number_input("Int20_TempOut_C (°C)", value=76.5)

with st.sidebar.expander("🔥 Módulo 2 (Calentamiento Crudo)", expanded=False):
    op_int00_tout = st.number_input("CalCrudo_Int00_TempOut_C (°C)", value=47.4)
    op_int0_tout = st.number_input("CalCrudo_Int0_TempOut_C (°C)", value=48.8)
    op_int1_tout = st.number_input("CalCrudo_Int1_TempOut_C (°C)", value=49.1)
    op_int2_tout = st.number_input("CalCrudo_Int2_TempOut_C (°C)", value=49.1)
    op_int3_tout = st.number_input("CalCrudo_Int3_TempOut_C (°C)", value=53.8)
    op_int3a_tout = st.number_input("CalCrudo_Int3a_TempOut_C (°C)", value=59.0)

with st.sidebar.expander("🧪 Módulo 3 (Depuración y Carb.)", expanded=False):
    op_cao_pct = st.slider("CaO_pct_remolacha (%)", 0.8, 2.0, 1.28, 0.01)
    op_corefin_th = st.number_input("AzucarCorefin_th (t/h)", value=8.80)
    op_alc1_in = st.number_input("1raCarb_AlcEntrada_gh (g/l)", value=2.50)
    op_alc1_out = st.number_input("1raCarb_AlcSalida (g/l)", value=0.90)
    op_alc2_out = st.number_input("2daCarb_AlcSalida (g/l)", value=0.27)
    op_pkf_ms = st.slider("PKF_MS_Barros_pct (%)", 50.0, 75.0, 64.9, 0.1)
    op_c3b_tin = st.number_input("Calent_3B_TempEntrada_C (°C)", value=61.4)
    op_c3b_tout = st.number_input("Calent_3B_TempSalida_C (°C)", value=65.5)
    op_c4_tout = st.number_input("Calent_4_TempSalida_C (°C)", value=82.3)
    op_c56_tout = st.number_input("Calent_56_TempSalida_C (°C)", value=87.8)
    op_c7_tout = st.number_input("Calent_7_TempSalida_C (°C)", value=87.8)
    op_enf_1carb = st.number_input("Enfriamiento_1raCarb_C (°C)", value=1.60)
    op_enf_1filt = st.number_input("Enfriamiento_1raFiltracion_C (°C)", value=1.00)
    op_enf_2carb = st.number_input("Enfriamiento_2daCarb_C (°C)", value=4.70)
    op_c8_tout = st.number_input("Calent_No8_TempSalida_C (°C)", value=86.2)
    op_c9_tout = st.number_input("Calent_No9_TempSalida_C (°C)", value=92.0)
    op_melting_pct = st.number_input("JugoFino_DestinoMelting_pct (%)", value=0.31)

with st.sidebar.expander("♨️ Módulo 4 (Thin Juice Heating)", expanded=False):
    op_c10_tout = st.number_input("Calentador10_TempSalida_C (°C)", value=117.3)
    op_c11_tout = st.number_input("Calentador11_12_TempSalida_C (°C)", value=121.6)
    op_c13_tout = st.number_input("Calentador13_TempSalida_C (°C)", value=123.8)
    op_c14_tout = st.number_input("Calentador14_TempSalida_C (°C)", value=123.8)

with st.sidebar.expander("💨 Módulo 5 (Evaporación)", expanded=False):
    op_evap_brix_obj = st.slider("Evaporacion_BrixSalida_objetivo_pct (%)", 60.0, 75.0, 69.4, 0.1)

with st.sidebar.expander("🍬 Módulo 6 (Cocimiento) & 9 (Energía)", expanded=False):
    op_brix_masa_a = st.slider("Cocimiento_BrixMasaA_pct (%)", 85.0, 95.0, 91.0, 0.1)
    op_brix_masa_b = st.slider("Cocimiento_BrixMasaB_pct (%)", 90.0, 98.0, 94.6, 0.1)
    op_brix_masa_c = st.slider("Cocimiento_BrixMasaC_pct (%)", 90.0, 98.0, 95.3, 0.1)
    op_pellet_hum = st.slider("Pulpa_HumedadPellet_pct (%)", 5.0, 15.0, 10.0, 0.1)
    op_gas_pci = st.number_input("SecaderoPulpa_PCI_Gas_kWh_m3", value=10.50)
    op_sec_rend = st.slider("SecaderoPulpa_RendimientoTérmico_pct (%)", 70.0, 95.0, 85.0, 1.0)
    op_turb_cons = st.number_input("Turbina_ConsumoEspecifico_kWh_tVapor", value=45.0)

config_usuario.update({
    'IN_Molienda_th': in_molienda, 'IN_Riqueza_Remolacha_pct': in_riqueza, 'IN_Pureza_Agricola_pct': in_pureza,
    'IN_Marc_Fibra_pct': in_marc, 'OP_DifPren_Ratio_Extraccion': op_ratio_ext, 'OP_DifPren_MS_PulpaPrensada_pct': op_ms_pulpa,
    'OP_DifPren_Temp_JugoCrudo_C': op_temp_crudo, 'OP_DifPren_Ratio_AguaAporte_pct': op_ratio_aporte,
    'OP_DifPren_Mezcla_AguaCaliente_pct': op_mezcla_caliente, 'OP_DifPren_Ratio_AguaPrensas_pct': op_ratio_prensas,
    'OP_DifPren_Ratio_Recirculacion_pct': op_ratio_recirc, 'OP_DifPren_Ratio_Desespumador_pct': op_ratio_desesp,
    'OP_DifPren_Int17_TempIn_C': op_int17_tin, 'OP_DifPren_Int17_TempOut_C': op_int17_tout,
    'OP_DifPren_Int18_19_TempIn_C': op_int18_tin, 'OP_DifPren_Int18_19_TempOut_C': op_int18_tout,
    'OP_DifPren_Int20_TempIn_C': op_int20_tin, 'OP_DifPren_Int20_TempOut_C': op_int20_tout,

    'OP_CalCrudo_Int00_TempOut_C': op_int00_tout, 'OP_CalCrudo_Int0_TempOut_C': op_int0_tout, 'OP_CalCrudo_Int1_TempOut_C': op_int1_tout,
    'OP_CalCrudo_Int2_TempOut_C': op_int2_tout, 'OP_CalCrudo_Int3_TempOut_C': op_int3_tout, 'OP_CalCrudo_Int3a_TempOut_C': op_int3a_tout,

    'OP_Depuracion_CaO_pct_remolacha': op_cao_pct, 'OP_AzucarCorefin_th': op_corefin_th, 'OP_1raCarb_AlcalinidadEntrada_gh': op_alc1_in,
    'OP_1raCarb_AlcalinidadSalida': op_alc1_out, 'OP_2daCarb_AlcalinidadSalida': op_alc2_out, 'OP_PKF_MS_Barros_pct': op_pkf_ms,
    'OP_Calent_3B_TempEntrada_C': op_c3b_tin, 'OP_Calent_3B_TempSalida_C': op_c3b_tout, 'OP_Calent_4_TempSalida_C': op_c4_tout,
    'OP_Calent_56_TempSalida_C': op_c56_tout, 'OP_Calent_7_TempSalida_C': op_c7_tout, 'OP_Enfriamiento_1raCarb_C': op_enf_1carb,
    'OP_Enfriamiento_1raFiltracion_C': op_enf_1filt, 'OP_Enfriamiento_2daCarb_C': op_enf_2carb, 'OP_Calent_No8_TempSalida_C': op_c8_tout,
    'OP_Calent_No9_TempSalida_C': op_c9_tout, 'OP_JugoFino_DestinoMelting_pct': op_melting_pct,

    'OP_Calentador10_TempSalida_C': op_c10_tout, 'OP_Calentador11_12_TempSalida_C': op_c11_tout, 'OP_Calentador13_TempSalida_C': op_c13_tout, 'OP_Calentador14_TempSalida_C': op_c14_tout,

    'OP_Evaporacion_BrixSalida_objetivo_pct': op_evap_brix_obj,
    'OP_Cocimiento_BrixMasaA_pct': op_brix_masa_a, 'OP_Cocimiento_BrixMasaB_pct': op_brix_masa_b, 'OP_Cocimiento_BrixMasaC_pct': op_brix_masa_c,
    'OP_Calentador15_Vapor_Fuente': 'Vapor_4toEfecto',
    'OP_Pulpa_HumedadPellet_pct': op_pellet_hum, 'OP_SecaderoPulpa_PCI_Gas_kWh_m3': op_gas_pci, 'OP_SecaderoPulpa_RendimientoTérmico_pct': op_sec_rend,
    'OP_Turbina_ConsumoEspecifico_kWh_tVapor': op_turb_cons
})

planta = PlantaAzucareraCompleta(config_usuario)
resultados = planta.simular()

tabs = st.tabs([
    "M1: Difusión", "M2: Cal Crudo", "M3: Depuración", "M4: Jugo Fino",
    "M5: Evaporación", "M6: Cocimiento", "M7: Refundición", "M8: Condensados",
    "M9: Energía", "📄 REPORTE MAESTRO"
])

def render_modulo_tab(mod_key, titulo):
    st.subheader(f"📊 Salidas del Balance: {titulo}")
    dict_data = {k: v for k, v in resultados[mod_key].items() if not isinstance(v, dict)}
    df = pd.DataFrame(list(dict_data.items()), columns=['Variable del Proceso', 'Valor Calculado'])
    st.dataframe(df, use_container_width=True, hide_index=True)

    for k, v in resultados[mod_key].items():
        if isinstance(v, dict):
            st.write(f"**Detalle: {k}**")
            st.json(v)

with tabs[0]: render_modulo_tab('M1', 'Módulo 1: Difusiones y Prensas')
with tabs[1]: render_modulo_tab('M2', 'Módulo 2: Calentamiento de Jugo Crudo')
with tabs[2]: render_modulo_tab('M3', 'Módulo 3: Depuración y Carbonataciones')
with tabs[3]: render_modulo_tab('M4', 'Módulo 4: Thin Juice Heating')
with tabs[4]: render_modulo_tab('M5', 'Módulo 5: Estación de Evaporación')
with tabs[5]: render_modulo_tab('M6', 'Módulo 6: Cocimiento y Cristalización')
with tabs[6]: render_modulo_tab('M7', 'Módulo 7: Refundición / Melter House')
with tabs[7]: render_modulo_tab('M8', 'Módulo 8: Circuito de Condensados')
with tabs[8]: render_modulo_tab('M9', 'Módulo 9: Secadero de Pulpa y Energía')

with tabs[9]:
    st.subheader("📄 Reporte Consolidado Íntegro")
    reporte_global = ""
    for m_key in ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9']:
        reporte_global += f"========================================================================\n"
        reporte_global += f" REPORTE MÓDULO: {m_key}\n"
        reporte_global += f"========================================================================\n"
        for k, v in resultados[m_key].items():
            if isinstance(v, dict):
                reporte_global += f"  • {k}:\n"
                for sub_k, sub_v in v.items():
                    reporte_global += f"      - {sub_k:<30}: {sub_v}\n"
            else:
                reporte_global += f"  • {k:<55}: {v}\n"
        reporte_global += "\n"

    st.text_area("Copia el reporte completo de la planta", reporte_global, height=600)
