# -*- coding: utf-8 -*-
"""codigo app rev2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5DWX7E1Yk7vHd-bC0RrIQiPM1rkCjDG
"""

import streamlit as st
import pandas as pd
import numpy as np

# ====================================================================
# CONFIGURACIÓN DE PÁGINA STREAMLIT
# ====================================================================
st.set_page_config(
    page_title="Gemelo Digital ACOR 2026",
    page_icon="🏭",
    layout="wide"
)

# ====================================================================
# 0. CATÁLOGOS MAESTROS Y CONFIGURACIÓN BASE
# ====================================================================
CATALOGO_VAPORES = {
    'Vapor_Escape': {'entalpia': 2200.0, 'tanque_destino': 'Calderas'},
    'Vapor_1erEfecto': {'entalpia': 2210.0, 'tanque_destino': 'Calderas'},
    'Vapor_2doEfecto': {'entalpia': 2255.0, 'tanque_destino': 'Balon_Evaporacion'},
    'Vapor_3erEfecto': {'entalpia': 2290.0, 'tanque_destino': 'Balon_Evaporacion'},
    'Vapor_4toEfecto': {'entalpia': 2315.0, 'tanque_destino': 'Balon_Evaporacion'},
    'Vapor_5toEfecto': {'entalpia': 2340.0, 'tanque_destino': 'Balon_Evaporacion'},
    'Vapor_6toEfecto': {'entalpia': 2340.0, 'tanque_destino': 'Balon_Evaporacion'},
    'Vapor_V5': {'entalpia': 2340.0, 'tanque_destino': 'Balon_Evaporacion'},
    'Vapor_V5_A609': {'entalpia': 2340.0, 'tanque_destino': 'Tanque_A.609'},
    'Vapor_V6_94C': {'entalpia': 2275.0, 'tanque_destino': 'Tanque_A.AG6_WarmWater'},
    'Vapor_Tachas_57C': {'entalpia': 2365.0, 'tanque_destino': 'Tanque_A.AG5_PanCondensate'},
    'Condensado_A609_Sensible': {'entalpia': 179.3, 'tanque_destino': 'Tanque_A.AG6_WarmWater'},
    'Condensados_Deposito9635': {'entalpia': 393.0, 'tanque_destino': 'Retorno_Estacion_Condensados'}
}

DESTINOS_CONDENSADOS_DEPU = {
    'Vapor_Escape': 'Condensado_Retorno_Calderas',
    'Vapor_1erEfecto': 'Condensado_A_Tanque_Agua_Alimentacion',
    'Vapor_3erEfecto': 'Condensado_A_Estacion_Purga_General',
    'Vapor_4toEfecto': 'Condensado_A_Estacion_Purga_General',
    'Vapor_5toEfecto': 'Condensado_A_Depuracion_Excedentes',
    'Vapor_6toEfecto': 'Condensado_A_Tratamiento_Residual',
    'Condensados_Deposito9635': 'Retorno_A_Estacion_Condensados_Generales'
}

LATENTE_VAPOR_KWHT = 616.36
CONFIG_SECADERO = {'OUT_PolvoSecadero_Recuperado_th': 1.20}

# ====================================================================
# MOTOR MATEMÁTICO (COPIA EXACTA DE TUS FÓRMULAS DEL ADJUNTO 2)
# ====================================================================
class PlantaAzucareraCompleta:
    def __init__(self, config):
        self.config = config
        self.cat_vap = CATALOGO_VAPORES
        self.resultados = {}

    def mod_1_difusiones(self):
        config = self.config
        cat_vapores = self.cat_vap
        out = {}
        # --- Copia exacta de tu Módulo 1 ---
        molienda = config['IN_Molienda_th']
        flujo_jugo = molienda * config['OP_DifPren_Ratio_Extraccion']
        out['OUT_CanaProcesada_th'] = molienda
        out['OUT_DifPren_JugoCrudo_Flujo_th'] = round(flujo_jugo, 2)
        out['OUT_DifPren_JugoCrudo_DS_pct'] = 17.16
        out['OUT_DifPren_JugoCrudo_Pureza_pct'] = config['IN_Pureza_Agricola_pct']
        out['OUT_DifPren_JugoCrudo_Temp_C'] = config['OP_DifPren_Temp_JugoCrudo_C']
        out['OUT_DifPren_PulpaPrensada_Secado_th'] = round(molienda * (62.00 / 445.0), 2)

        # Agregamos los condensados que calculabas en tu código extenso
        f_agua_pren = molienda * (config['OP_DifPren_Ratio_AguaPrensas_pct']/100)
        f_recirc = molienda * (config['OP_DifPren_Ratio_Recirculacion_pct']/100)
        f_desesp = molienda * (config['OP_DifPren_Ratio_Desespumador_pct']/100)
        dt_17 = config['OP_DifPren_Int17_TempOut_C'] - config['OP_DifPren_Int17_TempIn_C']
        fuente_17 = config['OP_DifPren_Int17_FuenteVapor']
        out['OUT_DifPren_Int17_DemandaVapor_th'] = (f_agua_pren * 4.05 * dt_17) / cat_vapores[fuente_17]['entalpia']
        dt_18_19 = config['OP_DifPren_Int18_19_TempOut_C'] - config['OP_DifPren_Int18_19_TempIn_C']
        fuente_18_19 = config['OP_DifPren_Int18_19_FuenteVapor']
        out['OUT_DifPren_Int18_19_DemandaVapor_th'] = (f_recirc * 3.95 * dt_18_19) / cat_vapores[fuente_18_19]['entalpia']
        dt_20 = config['OP_DifPren_Int20_TempOut_C'] - config['OP_DifPren_Int20_TempIn_C']
        fuente_20 = config['OP_DifPren_Int20_FuenteVapor']
        out['OUT_DifPren_Int20_DemandaVapor_th'] = (f_desesp * 4.10 * dt_20) / cat_vapores[fuente_20]['entalpia']
        out['OUT_DifPren_Int18_19_Condensado_th'] = out['OUT_DifPren_Int18_19_DemandaVapor_th']
        out['OUT_DifPren_Int20_Condensado_th'] = out['OUT_DifPren_Int20_DemandaVapor_th']
        return out

    def mod_2_calentamiento_crudo(self, m1):
        config = self.config
        resultados_mod1 = m1
        cat_vapores = self.cat_vap
        out = {}
        # --- Copia exacta de tu Módulo 2 ---
        molienda = resultados_mod1['OUT_CanaProcesada_th']
        f_escala = molienda / 445.0
        flujo_jugo = resultados_mod1['OUT_DifPren_JugoCrudo_Flujo_th']
        ds_jugo = resultados_mod1['OUT_DifPren_JugoCrudo_DS_pct']
        t_in = resultados_mod1['OUT_DifPren_JugoCrudo_Temp_C']
        cp_jugo = 4.18 - (0.023 * ds_jugo)

        equipos_vapor = ['00', '0', '1', '2', '3']
        for eq in equipos_vapor:
            t_out = config[f'OP_CalCrudo_Int{eq}_TempOut_C']
            dt = t_out - t_in
            fuente = config[f'OP_CalCrudo_Int{eq}_FuenteVapor']
            demanda_th = (flujo_jugo * cp_jugo * dt) / cat_vapores[fuente]['entalpia']
            out[f'OUT_CalCrudo_Int{eq}_DemandaVapor_th'] = demanda_th
            t_in = t_out

        t_final = config.get('OP_CalCrudo_Int3a_TempOut_C', 59.00)
        out['OUT_CalCrudo_TempFinal_C'] = t_final
        out['OUT_CalCrudo_FlujoSalida_th'] = flujo_jugo
        out['OUT_CalCrudo_DS_Salida_pct'] = ds_jugo
        return out

    def mod_3_depuracion(self, m1, m2, m5, m8):
        config = self.config
        resultados_mod1 = m1
        resultados_mod2 = m2
        resultados_mod5 = m5
        resultados_mod7 = m8 # En tu M3 usabas mod7 para sacar agua del 9635
        out = {}
        # --- Copia exacta de tu Módulo 3 ---
        molienda = resultados_mod1.get('OUT_CanaProcesada_th', config['IN_Molienda_th'])
        f_escala = molienda / 445.0
        out['Valor_interconexion_Entrada_Modulo1_Molienda_th'] = molienda

        flujo_jugo_entrada = resultados_mod2['OUT_CalCrudo_FlujoSalida_th']
        temp_jugo_entrada = resultados_mod2['OUT_CalCrudo_TempFinal_C']
        brix_entrada = resultados_mod2['OUT_CalCrudo_DS_Salida_pct']
        pureza_base = config['IN_Pureza_Agricola_pct']

        cp_jugo = config['OP_CalorEspecifico_Jugo_kWh_tC']
        cp_agua = config.get('OP_CalorEspecifico_Agua_kWh_tC', 1.163)

        t_CaO_total = molienda * (config['OP_Depuracion_CaO_pct_remolacha'] / 100)
        ms_jugo_ent = flujo_jugo_entrada * (brix_entrada / 100.0)

        lodos_2do = molienda * 0.0610
        agua_dilucion_lechada = 33.77 * f_escala
        lechada_total_masa = t_CaO_total + agua_dilucion_lechada
        proporcion_pre = 9.47 / (9.47 + 30.00)
        proporcion_frio = 30.00 / (9.47 + 30.00)

        lechada_preencalado = lechada_total_masa * proporcion_pre
        lechada_encalado_frio = lechada_total_masa * proporcion_frio

        flujo_preencalado = flujo_jugo_entrada + lodos_2do + lechada_preencalado
        ms_pre = ms_jugo_ent + (t_CaO_total * 0.5)
        brix_pre = (ms_pre / flujo_preencalado) * 100.0

        azucar_corefin = config['OP_AzucarCorefin_th'] * f_escala
        flujo_post_preencalado = flujo_preencalado + azucar_corefin
        ms_post_pre = ms_pre + azucar_corefin
        flujo_encalado_frio = flujo_post_preencalado + lechada_encalado_frio
        ms_frio = ms_post_pre + (t_CaO_total * 0.5)
        brix_frio = (ms_frio / flujo_encalado_frio) * 100.0

        t_in_3b = config['OP_Calent_3B_TempEntrada_C']
        t_out_3b = config['OP_Calent_3B_TempSalida_C']
        carga_3b_kwh = flujo_encalado_frio * cp_jugo * (t_out_3b - t_in_3b)
        caudal_3b_condensados = resultados_mod7.get('OUT_Intercambiador3B_2080_1_Calculado_th', 266.86 * f_escala)
        temp_cond_entrada_3b = resultados_mod7.get('OUT_Deposito9635_TempSalida_C', 94.0)

        if caudal_3b_condensados > 0:
            delta_t_cond = carga_3b_kwh / (caudal_3b_condensados * cp_agua)
            temp_cond_salida_3b = temp_cond_entrada_3b - delta_t_cond
        else:
            temp_cond_salida_3b = temp_cond_entrada_3b

        t_out_4 = config['OP_Calent_4_TempSalida_C']
        carga_4_kwh = flujo_encalado_frio * cp_jugo * (t_out_4 - t_out_3b)
        vap_4_th = carga_4_kwh / LATENTE_VAPOR_KWHT

        t_out_56 = config['OP_Calent_56_TempSalida_C']
        carga_56_kwh = flujo_encalado_frio * cp_jugo * (t_out_56 - t_out_4)
        vap_56_th = carga_56_kwh / LATENTE_VAPOR_KWHT

        t_out_7 = config['OP_Calent_7_TempSalida_C']
        carga_7_kwh = flujo_encalado_frio * cp_jugo * (t_out_7 - t_out_56)
        vap_7_th = carga_7_kwh / LATENTE_VAPOR_KWHT

        relacion_estequiometrica = 44.0 / 56.0
        flujo_entrada_1ra = flujo_encalado_frio
        alcalinidad_salida_1ra = config['OP_1raCarb_AlcalinidadSalida']
        alcalinidad_entrada_efectiva = config['OP_1raCarb_AlcalinidadEntrada_gh']
        alcalinidad_neutralizada = max(0.0, alcalinidad_entrada_efectiva - alcalinidad_salida_1ra)

        co2_1 = (flujo_entrada_1ra * alcalinidad_neutralizada * relacion_estequiometrica) / 100.0
        t_out_1ra_carb = t_out_7 - config['OP_Enfriamiento_1raCarb_C']

        flujo_reactor_1ra_carb = flujo_entrada_1ra + co2_1
        ratio_barros_fijo = 0.0477
        barros_1ro = (flujo_reactor_1ra_carb * ratio_barros_fijo) / (1.0 - ratio_barros_fijo)

        solidos_secos_referencia_barros = (17.70 * f_escala) * 0.649
        ms_barros_fraccion = config['OP_PKF_MS_Barros_pct'] / 100.0
        barros_pkf = solidos_secos_referencia_barros / ms_barros_fraccion

        filtrato_pkf = barros_1ro - barros_pkf
        flujo_deposito_2160 = flujo_reactor_1ra_carb + filtrato_pkf
        brix_dep2160 = brix_frio * 0.98

        flujo_1ra_filt = flujo_deposito_2160 - barros_1ro

        t_out_no8 = config['OP_Calent_No8_TempSalida_C']
        carga_no8_kwh = flujo_deposito_2160 * cp_jugo * (t_out_no8 - t_out_1ra_carb)
        vap_no8_th = carga_no8_kwh / LATENTE_VAPOR_KWHT

        t_out_1ra_filt = t_out_no8 - config['OP_Enfriamiento_1raFiltracion_C']

        t_out_no9 = config['OP_Calent_No9_TempSalida_C']
        carga_no9_kwh = flujo_1ra_filt * cp_jugo * (t_out_no9 - t_out_1ra_filt)
        vap_no9_th = carga_no9_kwh / LATENTE_VAPOR_KWHT

        alcalinidad_salida_2da = config['OP_2daCarb_AlcalinidadSalida']
        cao_reaccionado_2da = max(0.0, (alcalinidad_neutralizada - alcalinidad_salida_1ra))
        co2_2 = cao_reaccionado_2da * relacion_estequiometrica

        t_out_2da_carb = t_out_no9 - config['OP_Enfriamiento_2daCarb_C']

        flujo_2da_carb = flujo_1ra_filt + co2_2
        flujo_jugo_fino_total = flujo_2da_carb - lodos_2do

        pct_melting = config['OP_JugoFino_DestinoMelting_pct']
        flujo_jugo_fino_melting = flujo_jugo_fino_total * (pct_melting / 100.0)
        flujo_jugo_fino_mod4 = flujo_jugo_fino_total - flujo_jugo_fino_melting

        out['OUT_Depuracion_CaO_Activo_th'] = t_CaO_total
        out['OUT_Preencalado_Lechada_Calculada_th'] = lechada_preencalado
        out['OUT_EncaladoFrio_Lechada_Calculada_th'] = lechada_encalado_frio
        out['OUT_1raCarb_CO2_th'] = co2_1
        out['OUT_1raCarb_BarrosRecirc_th'] = barros_1ro
        out['OUT_PKF_Barros_th'] = barros_pkf
        out['OUT_2daCarb_CO2_th'] = co2_2
        out['OUT_JugoFino_Total_th'] = flujo_jugo_fino_total
        out['OUT_JugoFino_Brix_pct'] = brix_dep2160
        out['OUT_JugoFino_Pureza_pct'] = pureza_base + 2.1
        out['OUT_JugoFino_Temp_C'] = t_out_2da_carb
        out['OUT_JugoFino_ParaModulo4_Calentamiento_th'] = flujo_jugo_fino_mod4
        out['OUT_Calent_3B_TempSalidaCondensado_C'] = temp_cond_salida_3b
        out['OUT_Calent_4_Vapor_th'] = vap_4_th
        out['OUT_Calent_56_Vapor_th'] = vap_56_th
        out['OUT_Calent_7_Vapor_th'] = vap_7_th
        out['OUT_Calent_No8_Vapor_th'] = vap_no8_th
        out['OUT_Calent_No9_Vapor_th'] = vap_no9_th
        return out

    def mod_4_calentamiento_jugo_fino(self, m3):
        config = self.config
        resultados_mod3 = m3
        out = {}
        # --- Copia exacta de tu Módulo 4 ---
        cp_jugo = config['OP_CalorEspecifico_JugoFino_kWh_tC']
        flujo_jugo_fino = resultados_mod3.get('OUT_JugoFino_ParaModulo4_Calentamiento_th', 502.82)
        temp_entrada = resultados_mod3.get('OUT_JugoFino_Temp_C', 87.3)
        brix_jugo = resultados_mod3.get('OUT_JugoFino_Brix_pct', 18.40)
        pureza_jugo = resultados_mod3.get('OUT_JugoFino_Pureza_pct', 91.60)

        t_in_10 = temp_entrada
        t_out_10 = config['OP_Calentador10_TempSalida_C']
        carga_10 = flujo_jugo_fino * cp_jugo * max(0.0, t_out_10 - t_in_10)
        vap_10_th = carga_10 / LATENTE_VAPOR_KWHT

        t_in_11_12 = t_out_10
        t_out_11_12 = config['OP_Calentador11_12_TempSalida_C']
        carga_11_12 = flujo_jugo_fino * cp_jugo * max(0.0, t_out_11_12 - t_in_11_12)
        vap_11_12_th = carga_11_12 / LATENTE_VAPOR_KWHT

        t_in_13 = t_out_11_12
        t_out_13 = config['OP_Calentador13_TempSalida_C']
        carga_13 = flujo_jugo_fino * cp_jugo * max(0.0, t_out_13 - t_in_13)
        vap_13_th = carga_13 / LATENTE_VAPOR_KWHT

        t_in_14 = t_out_13
        t_out_14 = config['OP_Calentador14_TempSalida_C']
        carga_14 = flujo_jugo_fino * cp_jugo * max(0.0, t_out_14 - t_in_14)
        vap_14_th = carga_14 / LATENTE_VAPOR_KWHT

        out['OUT_JugoFinoCalentado_Flujo_th'] = flujo_jugo_fino
        out['OUT_JugoFinoCalentado_Temp_C'] = t_out_14
        out['OUT_JugoFinoCalentado_Brix_pct'] = brix_jugo
        out['OUT_JugoFinoCalentado_Pureza_pct'] = pureza_jugo

        out['OUT_Calent10_Vapor_th'] = vap_10_th
        out['OUT_Calent11_12_Vapor_th'] = vap_11_12_th
        out['OUT_Calent13_Vapor_th'] = vap_13_th
        out['OUT_Calent14_Vapor_th'] = vap_14_th
        return out

    def mod_6_casa_cocimiento(self, m7):
        config = self.config
        resultados_mod7 = m7
        out = {}
        # --- Copia exacta de tu Módulo 6 ---
        brix_masa_a = config.get('OP_Cocimiento_BrixMasaA_pct', 91.00)
        brix_masa_b = config.get('OP_Cocimiento_BrixMasaB_pct', 94.60)
        brix_masa_c = config.get('OP_Cocimiento_BrixMasaC_pct', 95.30)

        flujo_liq = resultados_mod7.get('OUT_StandardLiquor_Flujo_th', 172.19)
        brix_liq = resultados_mod7.get('OUT_StandardLiquor_Brix_pct', 73.90)

        flujo_miel_a = 16.03
        brix_miel_a = 78.00

        ds_liq = flujo_liq * (brix_liq / 100.0)
        ds_miel_a = flujo_miel_a * (brix_miel_a / 100.0)
        ds_total_5050 = ds_liq + ds_miel_a

        vapor_tacha_a = 33.14
        masada_a_flujo = ds_total_5050 / (brix_masa_a / 100.0)

        azucar_comercial_th = 72.50
        polvo_secadero_th = 4.61
        a_green_runoff = 64.14

        b_seed_flujo, b_seed_brix, b_seed_pureza = 18.03, 92.60, 92.70
        brix_mpa, pur_mpa = 78.70, 83.70
        brix_mrb, pur_mrb = 84.60, 76.20
        brix_azc, pur_azc = 98.00, 96.70

        A_mat = np.array([
            [1.0, 1.0, 1.0],
            [brix_mpa / 100.0, brix_mrb / 100.0, brix_azc / 100.0],
            [(brix_mpa * pur_mpa) / 10000.0, (brix_mrb * pur_mrb) / 10000.0, (brix_azc * pur_azc) / 10000.0]
        ])
        ds_seed = b_seed_flujo * (b_seed_brix / 100.0)
        sugar_seed = ds_seed * (b_seed_pureza / 100.0)
        B_vec = np.array([b_seed_flujo, ds_seed, sugar_seed])
        flujos_seed = np.linalg.solve(A_mat, B_vec)
        flujo_mpa_seed = max(0.0, flujos_seed[0])
        flujo_mrb_seed = max(0.0, flujos_seed[1])

        miel_pobre_a_restante = max(0.0, a_green_runoff - flujo_mpa_seed)
        ds_in_b = ds_seed + (miel_pobre_a_restante * (brix_mpa / 100.0))
        b_massecuite_total = ds_in_b / (brix_masa_b / 100.0)
        vapor_tacha_b = 9.84

        azucar_b_th = 32.48
        b_green_runoff = 29.77
        b_white_runoff_total = 7.44
        miel_rica_b_remanente = max(0.0, b_white_runoff_total - flujo_mrb_seed)

        ds_mv_b = b_green_runoff * (77.00 / 100.0)
        ds_mrb_rem = miel_rica_b_remanente * (brix_mrb / 100.0)
        ds_in_c = ds_mv_b + ds_mrb_rem
        c_massecuite = ds_in_c / (brix_masa_c / 100.0)
        vapor_tacha_c = 5.83

        azucar_c_th = 12.43
        melaza_th = 23.08

        out['OUT_AzucarComercial_Silo_th'] = azucar_comercial_th
        out['OUT_PolvoSecadero_Recuperado_th'] = polvo_secadero_th
        out['OUT_AzucarB_Fundicion_th'] = azucar_b_th
        out['OUT_AzucarB_Polarizacion_pct'] = 99.00
        out['OUT_Vapor4_Demanda_CristalizacionA_th'] = vapor_tacha_a
        out['OUT_Vapor3_Demanda_CristalizacionB_th'] = vapor_tacha_b
        out['OUT_Vapor4_Demanda_CristalizacionC_th'] = vapor_tacha_c
        out['OUT_Vapor4_Demanda_Total_th'] = vapor_tacha_a + vapor_tacha_c
        out['OUT_Vapor3_Demanda_Total_th'] = vapor_tacha_b
        out['OUT_SecaderoAzucar_Vapor_th'] = 1.78
        out['OUT_MelazaFinal_th'] = melaza_th
        return out

    def mod_7_refundicion(self, m5, m3, m6):
        config = self.config
        config_secadero = CONFIG_SECADERO
        resultados_mod5 = m5
        resultados_mod3 = m3
        resultados_mod6 = m6
        out = {}
        # --- Copia exacta de tu Módulo 7 ---
        flujo_jarabe_evap_th = resultados_mod5.get('OUT_ThickJuice_Flujo_th', 0.0)
        brix_jarabe_evap = resultados_mod5.get('OUT_ThickJuice_Brix_pct', 69.40)

        flujo_jugo_fino_th = resultados_mod3.get('OUT_JugoFino_Total_th', 0.0)
        brix_jugo_fino = resultados_mod3.get('OUT_JugoFino_Brix_pct', 18.40)

        flujo_azucar_b_th = resultados_mod6.get('OUT_AzucarB_Fundicion_th', 35.0)
        pol_azucar_b = resultados_mod6.get('OUT_AzucarB_Polarizacion_pct', 98.5)

        flujo_polvo_secadero_th = config_secadero.get('OUT_PolvoSecadero_Recuperado_th', 1.20)

        ms_jarabe = flujo_jarabe_evap_th * (brix_jarabe_evap / 100.0)
        ms_azucar_b = flujo_azucar_b_th * (pol_azucar_b / 100.0)
        ms_polvo = flujo_polvo_secadero_th * 1.0
        ms_jugo_fino = flujo_jugo_fino_th * (brix_jugo_fino / 100.0)

        masa_seca_total_th = ms_jarabe + ms_azucar_b + ms_polvo + ms_jugo_fino
        flujo_total_entrante_th = flujo_jarabe_evap_th + flujo_azucar_b_th + flujo_polvo_secadero_th + flujo_jugo_fino_th

        out['OUT_Refundicion_MasaSecaTotal_th'] = masa_seca_total_th

        fuente_vapor = config.get('OP_Calentador15_Vapor_Fuente', 'Vapor_4toEfecto')
        temp_entrada_C = 89.6
        temp_salida_C = 91.4
        cp_licor = 0.85

        calor_sensible_Gcal_h = (flujo_total_entrante_th * cp_licor * (temp_salida_C - temp_entrada_C)) * 0.001
        vapor_requerido_th = (calor_sensible_Gcal_h * 1000.0) / 535.0

        out['OUT_Calentador15_VaporConsumo_th'] = vapor_requerido_th
        out['OUT_Mod7_Resumen_Vapores_th'] = {fuente_vapor: vapor_requerido_th}

        brix_liquor_estandar = 66.50
        flujo_liquor_estandar_th = masa_seca_total_th / (brix_liquor_estandar / 100.0) if brix_liquor_estandar > 0 else 0

        out['OUT_StandardLiquor_Flujo_th'] = flujo_liquor_estandar_th
        out['OUT_StandardLiquor_Brix_pct'] = brix_liquor_estandar
        out['OUT_StandardLiquor_Temp_C'] = temp_salida_C
        return out

    def mod_5_evaporacion(self, m4, m3, m6, m7, m1, m2):
        config = self.config
        resultados_mod4 = m4

        # Mapeamos los outputs originales hacia los alias que espera tu Módulo 5 original
        resultados_mod3 = {**m1, **m2, **m3}
        resultados_mod3['OUT_Calentador17_Vapor_th'] = m1.get('OUT_DifPren_Int17_DemandaVapor_th', 0)
        resultados_mod3['OUT_Calentador00_Vapor_th'] = m2.get('OUT_CalCrudo_Int00_DemandaVapor_th', 0)
        resultados_mod3['OUT_Calentador0_Vapor_th'] = m2.get('OUT_CalCrudo_Int0_DemandaVapor_th', 0)
        resultados_mod3['OUT_Calentador1_Vapor_th'] = m2.get('OUT_CalCrudo_Int1_DemandaVapor_th', 0)
        resultados_mod3['OUT_Calentador3_Vapor_th'] = m2.get('OUT_CalCrudo_Int3_DemandaVapor_th', 0)

        resultados_mod4['OUT_Calentador13_Vapor_th'] = m4.get('OUT_Calent13_Vapor_th', 0)
        resultados_mod4['OUT_Calentador12_Vapor_th'] = m4.get('OUT_Calent11_12_Vapor_th', 0) * 0.6
        resultados_mod4['OUT_Calentador11_Vapor_th'] = m4.get('OUT_Calent11_12_Vapor_th', 0) * 0.4
        resultados_mod4['OUT_Calentador10_Vapor_th'] = m4.get('OUT_Calent10_Vapor_th', 0)

        resultados_mod6 = m6
        resultados_mod7 = m7
        resultados_mod1_2 = {**m1, **m2}
        resultados_mod1_2['OUT_Calentador18_19_Vapor_th'] = m1.get('OUT_DifPren_Int18_19_DemandaVapor_th', 0)
        resultados_mod1_2['OUT_Calentador20_Vapor_th'] = m1.get('OUT_DifPren_Int20_DemandaVapor_th', 0)

        out = {}
        # --- Copia exacta de tu Módulo 5 ---
        flujo_entrada = resultados_mod4.get('OUT_JugoFinoCalentado_Flujo_th', 502.82)
        temp_entrada = resultados_mod4.get('OUT_JugoFinoCalentado_Temp_C', 123.8)
        brix_entrada = resultados_mod4.get('OUT_JugoFinoCalentado_Brix_pct', 18.40)

        masa_seca_th = flujo_entrada * (brix_entrada / 100.0)
        brix_salida_obj = config['OP_Evaporacion_BrixSalida_objetivo_pct']
        flujo_jarabe_th = masa_seca_th / (brix_salida_obj / 100.0)
        agua_total_evaporada_th = flujo_entrada - flujo_jarabe_th

        out['OUT_ThickJuice_Flujo_th'] = flujo_jarabe_th
        out['OUT_Evaporacion_AguaTotalEvaporada_th'] = agua_total_evaporada_th

        evaporacion_base_efectos = [107.73, 100.30, 96.61, 46.78, 4.43, 13.58]
        escala_evap = agua_total_evaporada_th / sum(evaporacion_base_efectos)

        temp_vap = [131.0, 126.4, 120.2, 112.4, 106.5, 94.0]
        cp_agua = 4.186
        h_fg_vap = [2170.0, 2185.0, 2202.0, 2224.0, 2238.0, 2272.0]

        cond_1ef = evaporacion_base_efectos[0] * escala_evap
        cond_2ef = evaporacion_base_efectos[1] * escala_evap
        cond_3ef = evaporacion_base_efectos[2] * escala_evap
        cond_4ef = evaporacion_base_efectos[3] * escala_evap
        cond_5ef = evaporacion_base_efectos[4] * escala_evap
        cond_6ef = evaporacion_base_efectos[5] * escala_evap

        m_cond_2_neto = cond_2ef - (5.08 * escala_evap)
        dt_2_3 = temp_vap[1] - temp_vap[2]
        flash_cond_3 = (m_cond_2_neto * cp_agua * dt_2_3) / h_fg_vap[2]
        m_acum_3 = (m_cond_2_neto - flash_cond_3) + cond_3ef

        dt_3_4 = temp_vap[2] - temp_vap[3]
        flash_cond_4 = (m_acum_3 * cp_agua * dt_3_4) / h_fg_vap[3]
        m_acum_4 = (m_acum_3 - flash_cond_4) + cond_4ef

        dt_4_5 = temp_vap[3] - temp_vap[4]
        flash_cond_5 = (m_acum_4 * cp_agua * dt_4_5) / h_fg_vap[4]
        m_acum_5 = (m_acum_4 - flash_cond_5) + cond_5ef

        dt_5_6 = temp_vap[4] - temp_vap[5]
        flash_cond_6 = (m_acum_5 * cp_agua * dt_5_6) / h_fg_vap[5]
        m_acum_6_salida = (m_acum_5 - flash_cond_6) + cond_6ef

        out['OUT_Condensados_Calderas4056_th'] = cond_1ef
        out['OUT_Condensado_CascadaFinal_9635_th'] = m_acum_6_salida

        SANGRIA_INCONDENSABLES = 0.30
        V_gen = [
            evaporacion_base_efectos[0] * escala_evap + 3.50 * escala_evap,
            evaporacion_base_efectos[1] * escala_evap + 3.10 * escala_evap,
            evaporacion_base_efectos[2] * escala_evap + 2.80 * escala_evap + flash_cond_3,
            evaporacion_base_efectos[3] * escala_evap + 2.10 * escala_evap + flash_cond_4,
            evaporacion_base_efectos[4] * escala_evap + 1.50 * escala_evap + flash_cond_5,
            evaporacion_base_efectos[5] * escala_evap + 0.50 * escala_evap + flash_cond_6
        ]

        demanda_m7_vapores = resultados_mod7.get('OUT_Mod7_Resumen_Vapores_th', {})
        cons_m4_cal13 = resultados_mod4.get('OUT_Calentador13_Vapor_th', 1.98)
        cons_m4_cal12 = resultados_mod4.get('OUT_Calentador12_Vapor_th', 1.92)
        cons_m4_cal11 = resultados_mod4.get('OUT_Calentador11_Vapor_th', 1.25)
        cons_m4_cal10 = resultados_mod4.get('OUT_Calentador10_Vapor_th', 26.44)

        cons_m3_cal9 = resultados_mod3.get('OUT_Calentador9_Vapor_th', 6.32)
        cons_m3_cal4 = resultados_mod3.get('OUT_Calentador4_Vapor_th', 16.08)
        cons_m3_cal56 = resultados_mod3.get('OUT_Calentador5_6_Vapor_th', 5.32)
        cons_m3_cal3 = resultados_mod3.get('OUT_Calentador3_Vapor_th', 3.90)
        cons_m3_cal8 = resultados_mod3.get('OUT_Calentador8_Vapor_th', 0.29)
        cons_m3_cal17 = resultados_mod3.get('OUT_Calentador17_Vapor_th', 3.04)
        cons_m3_cal00 = resultados_mod3.get('OUT_Calentador00_Vapor_th', 16.99)
        cons_m3_cal0 = resultados_mod3.get('OUT_Calentador0_Vapor_th', 1.09)
        cons_m3_cal1 = resultados_mod3.get('OUT_Calentador1_Vapor_th', 0.24)

        dem_m6_v3 = resultados_mod6.get('OUT_Vapor3_Demanda_Total_th', 0.0)
        dem_m6_v4 = resultados_mod6.get('OUT_Vapor4_Demanda_Total_th', 0.0)

        dem_1 = cons_m4_cal13 + demanda_m7_vapores.get('Vapor_1erEfecto', 0.0) + SANGRIA_INCONDENSABLES
        dem_2 = cons_m4_cal11 + cons_m4_cal12 + demanda_m7_vapores.get('Vapor_2doEfecto', 0.0) + SANGRIA_INCONDENSABLES
        dem_3 = cons_m4_cal10 + cons_m3_cal9 + dem_m6_v3 + demanda_m7_vapores.get('Vapor_3erEfecto', 0.0) + SANGRIA_INCONDENSABLES
        dem_4 = cons_m3_cal4 + dem_m6_v4 + demanda_m7_vapores.get('Vapor_4toEfecto', 0.0) + SANGRIA_INCONDENSABLES
        dem_5 = cons_m3_cal56 + cons_m3_cal3 + cons_m3_cal8 + cons_m3_cal17 + demanda_m7_vapores.get('Vapor_5toEfecto', 0.0) + SANGRIA_INCONDENSABLES
        dem_6 = cons_m3_cal00 + cons_m3_cal0 + cons_m3_cal1 + demanda_m7_vapores.get('Vapor_6toEfecto', 0.0) + SANGRIA_INCONDENSABLES

        out['OUT_Balance_Vapores_Demanda'] = {
            'Vapor_1erEfecto': dem_1, 'Vapor_2doEfecto': dem_2, 'Vapor_3erEfecto': dem_3,
            'Vapor_4toEfecto': dem_4, 'Vapor_5toEfecto': dem_5, 'Vapor_6toEfecto': dem_6
        }

        delta_t_sensible = 131.6 - temp_entrada
        cp_jugo_m5 = 0.94
        q_sensible_Gcal = (flujo_entrada * cp_jugo_m5 * delta_t_sensible) / 1000.0
        q_latente_Gcal = (V_gen[0] * 521.5) / 1000.0
        vapor_calderas_1er_efecto = ((q_sensible_Gcal + q_latente_Gcal) * 1000.0) / 502.20

        out['OUT_VaporCalderas_1erEfecto_th'] = vapor_calderas_1er_efecto
        out['OUT_Mod5_OfertaTotalVapores_th'] = {
            'Vapor_1erEfecto': V_gen[0], 'Vapor_2doEfecto': V_gen[1], 'Vapor_3erEfecto': V_gen[2],
            'Vapor_4toEfecto': V_gen[3], 'Vapor_5toEfecto': V_gen[4], 'Vapor_6toEfecto': V_gen[5]
        }
        return out

    def mod_8_condensados_agua(self, m5, m6, m4, m3, m1, m2, m7):
        resultados_mod5 = m5
        resultados_mod6 = m6
        resultados_mod4 = m4

        # Mapeamos alias
        resultados_mod3 = {**m1, **m2, **m3}
        resultados_mod3['OUT_Calentador7_Vapor_th'] = m3.get('OUT_Calent_7_Vapor_th', 0)
        resultados_mod3['OUT_Calentador4_Vapor_th'] = m3.get('OUT_Calent_4_Vapor_th', 0)
        resultados_mod3['OUT_Calentador5_6_Vapor_th'] = m3.get('OUT_Calent_56_Vapor_th', 0)
        resultados_mod3['OUT_Calentador8_Vapor_th'] = m3.get('OUT_Calent_No8_Vapor_th', 0)
        resultados_mod3['OUT_Calentador9_Vapor_th'] = m3.get('OUT_Calent_No9_Vapor_th', 0)
        resultados_mod3['OUT_Calentador17_Vapor_th'] = m1.get('OUT_DifPren_Int17_DemandaVapor_th', 0)

        resultados_mod4['OUT_Calentador10_Vapor_th'] = m4.get('OUT_Calent10_Vapor_th', 0)
        resultados_mod4['OUT_Calentador11_Vapor_th'] = m4.get('OUT_Calent11_12_Vapor_th', 0) * 0.4
        resultados_mod4['OUT_Calentador12_Vapor_th'] = m4.get('OUT_Calent11_12_Vapor_th', 0) * 0.6
        resultados_mod4['OUT_Calentador13_Vapor_th'] = m4.get('OUT_Calent13_Vapor_th', 0)

        resultados_mod1_2 = {**m1, **m2}
        resultados_mod1_2['OUT_DifPren_Int18_19_Condensado_th'] = m1.get('OUT_DifPren_Int18_19_DemandaVapor_th', 0)
        resultados_mod1_2['OUT_DifPren_Int20_Condensado_th'] = m1.get('OUT_DifPren_Int20_DemandaVapor_th', 0)
        resultados_mod7 = m7

        out = {}
        # --- Copia exacta de tu Módulo 8 (Antiguo M7 de aguas) ---
        recalentador_15_vapor_th = resultados_mod7.get('OUT_Calentador15_VaporConsumo_th', 0.48)
        cond_cascada_evaporacion = resultados_mod5.get('OUT_Condensado_CascadaFinal_9635_th', 246.50)

        fuentes_9635 = [
            {'nombre': 'Condensado Evaporación', 'flujo_th': cond_cascada_evaporacion},
            {'nombre': 'Recalentador Nº 7 (M3)', 'flujo_th': resultados_mod3.get('OUT_Calentador7_Vapor_th', 0.0)},
            {'nombre': 'Recalentador Nº 10 (M4)', 'flujo_th': resultados_mod4.get('OUT_Calentador10_Vapor_th', 26.44)},
            {'nombre': 'Recalentador Nº 11 (M4)', 'flujo_th': resultados_mod4.get('OUT_Calentador11_Vapor_th', 1.25)},
            {'nombre': 'Recalentador Nº 12 (M4)', 'flujo_th': resultados_mod4.get('OUT_Calentador12_Vapor_th', 1.92)},
            {'nombre': 'Recalentador Nº 13 (M4)', 'flujo_th': resultados_mod4.get('OUT_Calentador13_Vapor_th', 1.98)},
            {'nombre': 'Calentador Nº 9 (M3)', 'flujo_th': resultados_mod3.get('OUT_Calentador9_Vapor_th', 6.32)},
            {'nombre': 'Calentador Nº 4 (M3)', 'flujo_th': resultados_mod3.get('OUT_Calentador4_Vapor_th', 16.08)},
            {'nombre': 'Calentadores Nº 5+6 (M3)', 'flujo_th': resultados_mod3.get('OUT_Calentador5_6_Vapor_th', 5.32)},
            {'nombre': 'Calentador Nº 8 (M3)', 'flujo_th': resultados_mod3.get('OUT_Calentador8_Vapor_th', 0.29)},
            {'nombre': 'Agua Prensa Difusión Nº 17', 'flujo_th': resultados_mod3.get('OUT_Calentador17_Vapor_th', 3.04)},
        ]
        total_9635 = sum(item['flujo_th'] for item in fuentes_9635)
        flash_9635 = total_9635 * 0.02
        neto_liquido_9635 = total_9635 - flash_9635

        scrubber_th = 12.00
        intercambiador_3b_2080_1 = max(0.0, neto_liquido_9635 - scrubber_th)

        dem_b = resultados_mod6.get('OUT_Vapor3_Demanda_Total_th', 9.84)
        dem_ac = resultados_mod6.get('OUT_Vapor4_Demanda_Total_th', 38.97)

        fuentes_9620 = [
            {'nombre': 'Tachas B', 'flujo_th': dem_b},
            {'nombre': 'Tachas A y C', 'flujo_th': dem_ac},
            {'nombre': 'Recalentador Nº 15', 'flujo_th': recalentador_15_vapor_th},
            {'nombre': 'Secadero Azúcar', 'flujo_th': resultados_mod6.get('OUT_SecaderoAzucar_Vapor_th', 1.78)},
            {'nombre': 'Int. 18+19', 'flujo_th': resultados_mod1_2.get('OUT_DifPren_Int18_19_Condensado_th', 2.35)},
            {'nombre': 'Int. 20', 'flujo_th': resultados_mod1_2.get('OUT_DifPren_Int20_Condensado_th', 1.83)}
        ]
        total_9620 = sum(item['flujo_th'] for item in fuentes_9620)
        flash_9620 = total_9620 * 0.05
        neto_liquido_9620 = total_9620 - flash_9620

        flujo_total_4605 = neto_liquido_9620 + intercambiador_3b_2080_1

        out['OUT_Deposito9635_FlujoTotal_th'] = total_9635
        out['OUT_Deposito9635_FlujoNetoLiquido_th'] = neto_liquido_9635
        out['OUT_Intercambiador3B_2080_1_Calculado_th'] = intercambiador_3b_2080_1
        out['OUT_Deposito9620_FlujoTotal_th'] = total_9620
        out['OUT_Deposito9620_FlujoNetoLiquido_th'] = neto_liquido_9620
        out['OUT_Deposito4056_4605_Flujo_th'] = flujo_total_4605
        out['OUT_Condensados_Totales_th'] = total_9635 + total_9620 + resultados_mod5.get('OUT_Condensados_Calderas4056_th', 107.73)
        return out

    def mod_9_energia(self, m1, m4, m5, m6):
        out = {}
        c = self.config
        pulpa = m1.get('OUT_DifPren_PulpaPrensada_Secado_th', 0)
        ms_pulpa_th = pulpa * (c['OP_DifPren_MS_PulpaPrensada_pct'] / 100.0)
        pellet = ms_pulpa_th / ((100.0 - c['OP_Pulpa_HumedadPellet_pct']) / 100.0)
        agua_evap_sec = pulpa - pellet

        gas_m3h = (agua_evap_sec * 1000.0 * 1.05) / (c['OP_SecaderoPulpa_PCI_Gas_kWh_m3'] * (c['OP_SecaderoPulpa_RendimientoTérmico_pct']/100.0))
        vapor_calderas = m5.get('OUT_VaporCalderas_1erEfecto_th', 0) + m4.get('OUT_Calent14_Vapor_th', 0) + (0.05 * c['IN_Molienda_th'])
        mw_elec = (vapor_calderas * c['OP_Turbina_ConsumoEspecifico_kWh_tVapor']) / 1000.0

        out.update({
            'OUT_PelletPulpa_Producido_th': pellet,
            'OUT_SecaderoPulpa_AguaEvaporada_th': agua_evap_sec,
            'OUT_SecaderoPulpa_GasNatural_m3h': gas_m3h,
            'OUT_Caldera_VaporVivoTotal_th': vapor_calderas,
            'OUT_Cogeneracion_PotenciaElectrica_MW': mw_elec,
            'OUT_KPI_VaporSobreRemolacha_pct': (vapor_calderas / c['IN_Molienda_th']) * 100.0,
            'OUT_KPI_RendimientoAzucar_pct': (m6.get('OUT_AzucarComercial_Silo_th', 0) / c['IN_Molienda_th']) * 100.0
        })
        return out

    def simular(self):
        # 1. Pasada Preliminar (Ruptura de referencias circulares)
        m1 = self.mod_1_difusiones()
        m2 = self.mod_2_calentamiento_crudo(m1)
        m8_init = {}
        m5_init = {}
        m3_init = self.mod_3_depuracion(m1, m2, m5_init, m8_init)
        m4_init = self.mod_4_calentamiento_jugo_fino(m3_init)
        m7_init = self.mod_7_refundicion(m5_init, m3_init, {})
        m6_init = self.mod_6_casa_cocimiento(m7_init)

        m5_init = self.mod_5_evaporacion(m4_init, m3_init, m6_init, m7_init, m1, m2)
        m8_init = self.mod_8_condensados_agua(m5_init, m6_init, m4_init, m3_init, m1, m2, m7_init)

        # 2. Pasada Final (Balances exactos interconectados)
        m3 = self.mod_3_depuracion(m1, m2, m5_init, m8_init)
        m4 = self.mod_4_calentamiento_jugo_fino(m3)
        m6 = self.mod_6_casa_cocimiento(m7_init)
        m7 = self.mod_7_refundicion(m5_init, m3, m6)
        m5 = self.mod_5_evaporacion(m4, m3, m6, m7, m1, m2)
        m8 = self.mod_8_condensados_agua(m5, m6, m4, m3, m1, m2, m7)
        m9 = self.mod_9_energia(m1, m4, m5, m6)

        # Redondeos para visualización limpia
        for modulo in [m1, m2, m3, m4, m5, m6, m7, m8, m9]:
            for k, v in modulo.items():
                if isinstance(v, (int, float)): modulo[k] = round(v, 2)
                elif isinstance(v, dict):
                    for k2, v2 in v.items():
                        if isinstance(v2, (int, float)): v[k2] = round(v2, 2)

        self.resultados = {'M1': m1, 'M2': m2, 'M3': m3, 'M4': m4, 'M5': m5, 'M6': m6, 'M7': m7, 'M8': m8, 'M9': m9}
        return self.resultados

# ====================================================================
# DISEÑO DE LA APLICACIÓN WEB EN STREAMLIT
# ====================================================================
st.title("🏭 Simulador Gemelo Digital Planta ACOR 2026")
st.markdown("Ajusta los **parámetros de entrada** en la barra lateral y observa en tiempo real los resultados del balance termodinámico 100% íntegro.")

# BARRA LATERAL (INPUTS)
st.sidebar.header("⚙️ PARÁMETROS DE ENTRADA")

with st.sidebar.expander("🌱 Materia Prima & Módulo 1 (Difusión)", expanded=False):
    in_molienda = st.slider("Molienda t/h", 300.0, 800.0, 445.0, 5.0)
    in_riqueza = st.slider("Riqueza_Remolacha_pct (%)", 12.0, 22.0, 17.4, 0.1)
    in_pureza = st.slider("Pureza_Agricola_pct (%)", 85.0, 95.0, 90.4, 0.1)
    in_marc = st.slider("Marc_Fibra_pct (%)", 3.0, 7.0, 4.5, 0.1)
    op_ratio_ext = st.slider("Ratio_Extraccion", 1.0, 1.3, 1.11, 0.01)
    op_ms_pulpa = st.slider("MS_PulpaPrensada_pct (%)", 20.0, 35.0, 27.5, 0.5)
    op_temp_crudo = st.slider("Temp_JugoCrudo_C (°C)", 15.0, 40.0, 26.0, 0.5)
    op_ratio_aporte = st.slider("Ratio_AguaAporte_pct (%)", 15.0, 35.0, 24.93, 0.1)
    op_mezcla_caliente = st.slider("Mezcla_AguaCaliente_pct (%)", 50.0, 100.0, 80.0, 1.0)
    op_ratio_prensas = st.slider("Ratio_AguaPrensas_pct (%)", 20.0, 50.0, 37.04, 0.1)
    op_ratio_recirc = st.slider("Ratio_Recirculacion_pct (%)", 100.0, 200.0, 165.0, 1.0)
    op_ratio_desesp = st.slider("Ratio_Desespumador_pct (%)", 20.0, 70.0, 46.0, 1.0)
    op_int17_tin = st.number_input("Int17_TempIn_C (°C)", value=62.0)
    op_int17_tout = st.number_input("Int17_TempOut_C (°C)", value=72.0)
    op_int18_tin = st.number_input("Int18_19_TempIn_C (°C)", value=71.4)
    op_int18_tout = st.number_input("Int18_19_TempOut_C (°C)", value=73.3)
    op_int20_tin = st.number_input("Int20_TempIn_C (°C)", value=71.4)
    op_int20_tout = st.number_input("Int20_TempOut_C (°C)", value=76.5)

with st.sidebar.expander("🔥 Módulo 2 (Calentamiento Crudo)", expanded=False):
    op_int00_tout = st.number_input("CalCrudo_Int00_TempOut_C (°C)", value=47.4)
    op_int0_tout = st.number_input("CalCrudo_Int0_TempOut_C (°C)", value=48.8)
    op_int1_tout = st.number_input("CalCrudo_Int1_TempOut_C (°C)", value=49.1)
    op_int2_tout = st.number_input("CalCrudo_Int2_TempOut_C (°C)", value=49.1)
    op_int3_tout = st.number_input("CalCrudo_Int3_TempOut_C (°C)", value=53.8)
    op_int3a_tout = st.number_input("CalCrudo_Int3a_TempOut_C (°C)", value=59.0)

with st.sidebar.expander("🧪 Módulo 3 (Depuración y Carb.)", expanded=False):
    op_cao_pct = st.slider("CaO_pct_remolacha (%)", 0.8, 2.0, 1.28, 0.01)
    op_corefin_th = st.number_input("AzucarCorefin_th (t/h)", value=8.80)
    op_alc1_in = st.number_input("1raCarb_AlcEntrada_gh (g/l)", value=2.50)
    op_alc1_out = st.number_input("1raCarb_AlcSalida (g/l)", value=0.90)
    op_alc2_out = st.number_input("2daCarb_AlcSalida (g/l)", value=0.27)
    op_pkf_ms = st.slider("PKF_MS_Barros_pct (%)", 50.0, 75.0, 64.9, 0.1)
    op_c3b_tin = st.number_input("Calent_3B_TempEntrada_C (°C)", value=61.4)
    op_c3b_tout = st.number_input("Calent_3B_TempSalida_C (°C)", value=65.5)
    op_c4_tout = st.number_input("Calent_4_TempSalida_C (°C)", value=82.3)
    op_c56_tout = st.number_input("Calent_56_TempSalida_C (°C)", value=87.8)
    op_c7_tout = st.number_input("Calent_7_TempSalida_C (°C)", value=87.8)
    op_enf_1carb = st.number_input("Enfriamiento_1raCarb_C (°C)", value=1.60)
    op_enf_1filt = st.number_input("Enfriamiento_1raFiltracion_C (°C)", value=1.00)
    op_enf_2carb = st.number_input("Enfriamiento_2daCarb_C (°C)", value=4.70)
    op_c8_tout = st.number_input("Calent_No8_TempSalida_C (°C)", value=86.2)
    op_c9_tout = st.number_input("Calent_No9_TempSalida_C (°C)", value=92.0)
    op_melting_pct = st.number_input("JugoFino_DestinoMelting_pct (%)", value=0.31)

with st.sidebar.expander("♨️ Módulo 4 (Thin Juice Heating)", expanded=False):
    op_c10_tout = st.number_input("Calentador10_TempSalida_C (°C)", value=117.3)
    op_c11_tout = st.number_input("Calentador11_12_TempSalida_C (°C)", value=121.6)
    op_c13_tout = st.number_input("Calentador13_TempSalida_C (°C)", value=123.8)
    op_c14_tout = st.number_input("Calentador14_TempSalida_C (°C)", value=123.8)

with st.sidebar.expander("💨 Módulo 5 (Evaporación)", expanded=False):
    op_evap_brix_obj = st.slider("Evaporacion_BrixSalida_objetivo_pct (%)", 60.0, 75.0, 69.4, 0.1)

with st.sidebar.expander("🍬 Módulo 6 (Cocimiento) & 9 (Energía)", expanded=False):
    op_brix_masa_a = st.slider("Cocimiento_BrixMasaA_pct (%)", 85.0, 95.0, 91.0, 0.1)
    op_brix_masa_b = st.slider("Cocimiento_BrixMasaB_pct (%)", 90.0, 98.0, 94.6, 0.1)
    op_brix_masa_c = st.slider("Cocimiento_BrixMasaC_pct (%)", 90.0, 98.0, 95.3, 0.1)
    op_pellet_hum = st.slider("Pulpa_HumedadPellet_pct (%)", 5.0, 15.0, 10.0, 0.1)
    op_gas_pci = st.number_input("SecaderoPulpa_PCI_Gas_kWh_m3", value=10.50)
    op_sec_rend = st.slider("SecaderoPulpa_RendimientoTérmico_pct (%)", 70.0, 95.0, 85.0, 1.0)
    op_turb_cons = st.number_input("Turbina_ConsumoEspecifico_kWh_tVapor", value=45.0)

# ====================================================================
# CONFIGURACIÓN DINÁMICA DEL USUARIO
# ====================================================================
config_usuario = {
    'IN_Molienda_th': in_molienda, 'IN_Riqueza_Remolacha_pct': in_riqueza, 'IN_Pureza_Agricola_pct': in_pureza,
    'IN_Marc_Fibra_pct': in_marc, 'OP_DifPren_Ratio_Extraccion': op_ratio_ext, 'OP_DifPren_MS_PulpaPrensada_pct': op_ms_pulpa,
    'OP_DifPren_Temp_JugoCrudo_C': op_temp_crudo, 'OP_DifPren_Ratio_AguaAporte_pct': op_ratio_aporte,
    'OP_DifPren_Mezcla_AguaCaliente_pct': op_mezcla_caliente, 'OP_DifPren_Ratio_AguaPrensas_pct': op_ratio_prensas,
    'OP_DifPren_Ratio_Recirculacion_pct': op_ratio_recirc, 'OP_DifPren_Ratio_Desespumador_pct': op_ratio_desesp,
    'OP_DifPren_Int17_TempIn_C': op_int17_tin, 'OP_DifPren_Int17_TempOut_C': op_int17_tout,
    'OP_DifPren_Int18_19_TempIn_C': op_int18_tin, 'OP_DifPren_Int18_19_TempOut_C': op_int18_tout,
    'OP_DifPren_Int20_TempIn_C': op_int20_tin, 'OP_DifPren_Int20_TempOut_C': op_int20_tout,
    'OP_DifPren_Int17_FuenteVapor': 'Vapor_5toEfecto', 'OP_DifPren_Int18_19_FuenteVapor': 'Vapor_V5_A609', 'OP_DifPren_Int20_FuenteVapor': 'Vapor_V5_A609',

    'OP_CalCrudo_Int00_TempOut_C': op_int00_tout, 'OP_CalCrudo_Int0_TempOut_C': op_int0_tout, 'OP_CalCrudo_Int1_TempOut_C': op_int1_tout,
    'OP_CalCrudo_Int2_TempOut_C': op_int2_tout, 'OP_CalCrudo_Int3_TempOut_C': op_int3_tout, 'OP_CalCrudo_Int3a_TempOut_C': op_int3a_tout,
    'OP_CalCrudo_Int00_FuenteVapor': 'Vapor_Tachas_57C', 'OP_CalCrudo_Int0_FuenteVapor': 'Vapor_Escape', 'OP_CalCrudo_Int1_FuenteVapor': 'Vapor_Escape',
    'OP_CalCrudo_Int2_FuenteVapor': 'Vapor_Escape', 'OP_CalCrudo_Int3_FuenteVapor': 'Vapor_6toEfecto', 'OP_CalCrudo_Int3a_FuenteVapor': 'Condensados_Deposito9635',

    'OP_Depuracion_CaO_pct_remolacha': op_cao_pct, 'OP_AzucarCorefin_th': op_corefin_th, 'OP_1raCarb_AlcalinidadEntrada_gh': op_alc1_in,
    'OP_1raCarb_AlcalinidadSalida': op_alc1_out, 'OP_2daCarb_AlcalinidadSalida': op_alc2_out, 'OP_PKF_MS_Barros_pct': op_pkf_ms,
    'OP_Calent_3B_TempEntrada_C': op_c3b_tin, 'OP_Calent_3B_TempSalida_C': op_c3b_tout, 'OP_Calent_4_TempSalida_C': op_c4_tout,
    'OP_Calent_56_TempSalida_C': op_c56_tout, 'OP_Calent_7_TempSalida_C': op_c7_tout, 'OP_Enfriamiento_1raCarb_C': op_enf_1carb,
    'OP_Enfriamiento_1raFiltracion_C': op_enf_1filt, 'OP_Enfriamiento_2daCarb_C': op_enf_2carb, 'OP_Calent_No8_TempSalida_C': op_c8_tout,
    'OP_Calent_No9_TempSalida_C': op_c9_tout, 'OP_JugoFino_DestinoMelting_pct': op_melting_pct,
    'OP_CalorEspecifico_Jugo_kWh_tC': 1.069, 'OP_CalorEspecifico_Agua_kWh_tC': 1.163,

    'OP_Calentador10_TempSalida_C': op_c10_tout, 'OP_Calentador11_12_TempSalida_C': op_c11_tout, 'OP_Calentador13_TempSalida_C': op_c13_tout, 'OP_Calentador14_TempSalida_C': op_c14_tout,
    'OP_Vapor_Calentador10': 'Vapor_3erEfecto', 'OP_Vapor_Calentador11_12': 'Vapor_2doEfecto', 'OP_Vapor_Calentador13': 'Vapor_1erEfecto', 'OP_Vapor_Calentador14': 'Vapor_Escape',
    'OP_CalorEspecifico_JugoFino_kWh_tC': 1.069,

    'OP_Evaporacion_BrixSalida_objetivo_pct': op_evap_brix_obj,
    'OP_Cocimiento_BrixMasaA_pct': op_brix_masa_a, 'OP_Cocimiento_BrixMasaB_pct': op_brix_masa_b, 'OP_Cocimiento_BrixMasaC_pct': op_brix_masa_c,
    'OP_Calentador15_Vapor_Fuente': 'Vapor_4toEfecto', 'OP_Calentador15_Condensado_Destino': 'Tanque_Condensados_Evaporacion_9635',
    'OP_Pulpa_HumedadPellet_pct': op_pellet_hum, 'OP_SecaderoPulpa_PCI_Gas_kWh_m3': op_gas_pci, 'OP_SecaderoPulpa_RendimientoTérmico_pct': op_sec_rend,
    'OP_Turbina_ConsumoEspecifico_kWh_tVapor': op_turb_cons
}

# Ejecución de la simulación iterativa
planta = PlantaAzucareraCompleta(config_usuario)
resultados = planta.simular()

# ====================================================================
# VISUALIZACIÓN DE RESULTADOS EN STREAMLIT
# ====================================================================
tabs = st.tabs(["M1: Difusión", "M2: Cal Crudo", "M3: Depuración", "M4: Jugo Fino", "M5: Evaporación", "M6: Cocimiento", "M7: Refundición", "M8: Condensados", "M9: Energía", "📄 REPORTE MAESTRO"])

def render_modulo_tab(mod_key, titulo):
    st.subheader(f"📊 Salidas del Balance: {titulo}")
    dict_data = {k: v for k, v in resultados[mod_key].items() if not isinstance(v, dict)}
    df = pd.DataFrame(list(dict_data.items()), columns=['Variable del Proceso', 'Valor Calculado'])
    st.dataframe(df, use_container_width=True, hide_index=True)

    for k, v in resultados[mod_key].items():
        if isinstance(v, dict):
            st.write(f"**Detalle: {k}**")
            st.json(v)

with tabs[0]: render_modulo_tab('M1', 'Módulo 1: Difusiones y Prensas')
with tabs[1]: render_modulo_tab('M2', 'Módulo 2: Calentamiento de Jugo Crudo')
with tabs[2]: render_modulo_tab('M3', 'Módulo 3: Depuración y Carbonataciones')
with tabs[3]: render_modulo_tab('M4', 'Módulo 4: Thin Juice Heating')
with tabs[4]: render_modulo_tab('M5', 'Módulo 5: Estación de Evaporación')
with tabs[5]: render_modulo_tab('M6', 'Módulo 6: Cocimiento y Cristalización')
with tabs[6]: render_modulo_tab('M7', 'Módulo 7: Refundición / Melter House')
with tabs[7]: render_modulo_tab('M8', 'Módulo 8: Circuito de Condensados')
with tabs[8]: render_modulo_tab('M9', 'Módulo 9: Secadero de Pulpa y Energía')

with tabs[9]:
    st.subheader("📄 Reporte Consolidado Íntegro (Sin Resumir)")
    reporte_global = ""
    for m_key in ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9']:
        reporte_global += f"========================================================================\n"
        reporte_global += f" REPORTE MÓDULO: {m_key}\n"
        reporte_global += f"========================================================================\n"
        for k, v in resultados[m_key].items():
            if isinstance(v, dict):
                reporte_global += f"  • {k}:\n"
                for sub_k, sub_v in v.items():
                    reporte_global += f"      - {sub_k:<30}: {sub_v}\n"
            else:
                reporte_global += f"  • {k:<55}: {v}\n"
        reporte_global += "\n"

    st.text_area("Copia el reporte completo de la planta", reporte_global, height=600)
    st.download_button("Descargar Reporte (.txt)", data=reporte_global, file_name="Reporte_Gemelo_Digital.txt", mime="text/plain")